### ISSUE TITLE
libpng warning messages.

### ISSUE THREAD

**Issue by r3v** [mapcrafter/mapcrafter#121]
Running on OS X (Yosemite).  I get these libpng warnings during the "Scanning required tiles..." section.

    libpng warning: iCCP: known incorrect sRGB profile

I get 19 of them for each rendering pass.  They appear to be innocuous, but do make for a messy and much longer than necessary output.  

From reading a stackoverflow conversation on the warning, it seems to be caused by Libpng-1.6 being "more stringent about checking ICC profiles".  Apparently, these bad profiles can be removed with ImageMagick/mogrify... but I'm not even certain which png files libpng is complaining about. There are 14 png files in the source and 381 more in the textures directory.

I don't know much about the png format or imagemagick. Is it safe to run mogrify on all of these files? Or am I barking up the wrong tree here and should look for a different fix for this libpng warning?

**Comment by m0r13** [comment]
Hmm. Can you run it again and post the exact output here?

**Comment by r3v** [comment]
Sure: 

	%  ~/tmp/mapcrafter/src/tools/mapcrafter_textures.py /Users/cls/Library/Application\ Support/minecraft/versions/1.8.1/1.8.1.jar ~/.mapcrafter/textures2
	Extracting block images:
	 - Found 382 block images.
	 - Extracted 382.
	 - Skipped 0 (Use -f to force overwrite).

	Extracting other textures:
	 - Extracting /Users/cls/.mapcrafter/textures2/entity/chest/normal.png ... extracted.
	 - Extracting /Users/cls/.mapcrafter/textures2/entity/chest/normal_double.png ... extracted.
	 - Extracting /Users/cls/.mapcrafter/textures2/entity/chest/ender.png ... extracted.
	 - Extracting /Users/cls/.mapcrafter/textures2/entity/chest/trapped.png ... extracted.
	 - Extracting /Users/cls/.mapcrafter/textures2/entity/chest/trapped_double.png ... extracted.
	 - Extracting /Users/cls/.mapcrafter/textures2/colormap/foliage.png ... extracted.
	 - Extracting /Users/cls/.mapcrafter/textures2/colormap/grass.png ... extracted.

**Comment by m0r13** [comment]
I'm sorry, I forgot a bit about this. Are you sure that Mapcrafter is using exactly this texture directory or maybe also another system-wide directory (you can check this by running ``mapcrafter --find-resources``)?

You could also try to run imagemagick manually on your texture files. I'll search the required commands for you. Otherwise if that also doesn't help... which version of imagemagick do you have? Maybe your imagemagick doesn't really fix the color profiles, I'm not really sure.

**Comment by r3v** [comment]
No worries, I did too, since the error has gone away.  I'm not sure what caused it to disappear.. but it has. So, I'm fine if you want to close this.
