### ISSUE TITLE
Some textures not rendering correctly in 1.5.3

### ISSUE THREAD

**Issue by rockmacaca** [mapcrafter/mapcrafter#122]
A couple things: I'm using Windows 64bit, and a fresh installation of 1.5.3.

Some blocks are rendered transparent with some faint weird artifacts in their place. 
![](http://i.imgur.com/1sGOMhf.png) <-- there is supposed to cyan hardened clay here

I haven't tested anything extensively, but I think I've narrowed it down to the bit-depth of the textures. All of the textures included in 1.5.3 are 32 bit EXCEPT for all the hardened clay textures and red sand, which are 8 bit. Replacing the hardened clay and red sand textures with the 32 bit versions from the 1.5.0 zip seems to have fixed my problems. However this results in a bunch of incorrect sRGB profile warnings from libpng.

 Oddly enough, spruce doors are 24 bit while all other doors are 32 bit. However, I think it is only the 8 bit PNGs that are causing problems, again, I haven't tested it out much.

**Comment by m0r13** [comment]
You are right, it seems that the newer hardened clay textures have an indexed palette-based color format (8 bit), whereas the other textures are 24 bit (RGB) or 32 bit (RGBA). Mapcrafter is able to handle 24- and 32 bit images, but not the indexed 8 bit images. A possible solution could be to convert all those textures with imagemagick, but I think the better solution would be that I have a look at the libpng documentation again and find out how to read those 8 bit images too.

**Comment by m0r13** [comment]
I was able to figure out how to read indexed images with libpng, also Mapcrafter should be able to read gray-scale images and various combinations of indexed / gray-scale colors with different bit depths per channel and alpha / no alpha channel now.
