### ISSUE TITLE
Unable to change map on touch devices

### ISSUE THREAD

**Issue by zacschutt** [mapcrafter/mapcrafter#123]
When using a touch device, I am unable to use the map selection drop down. On the PC, I need to use the arrow keys to select the world. This is not just a bug in my installation, it affects all installations that i have seen.

**Comment by jonathanpenn** [comment]
I'm experiencing this, too. I'm viewing the generated maps on the iPad Air 2 (latest released version of iOS 8). When tapping on the combo control to choose the map type, it just behaves as if I tapped on the map.

**Comment by tripkin** [comment]
I am also experiencing this on my BBZ10. The map load is quick, zoom and pan are very fast, I can change orientation, and everything else is good. Just the map selector tool does not seem to work other than to show that it has been pressed. I rendered my maps with Mapcrafter version: 2.1 (v.2.1-1-g75cad59).
