### ISSUE TITLE
This file requires compiler and library support for the ISO C++ 2011 standard

### ISSUE THREAD

**Issue by samupl** [mapcrafter/mapcrafter#124]
Consider adding `add_compile_options(-std=c++0x)` at the top of CMakeLists.txt

**Comment by thorerik** [comment]
https://github.com/mapcrafter/mapcrafter/blob/master/CMakeLists.txt#L36

**Comment by m0r13** [comment]
I guess you get a compiler error that you have to enable C++11 features? Can you post the output of cmake and make after you deleted ``CMakeFiles/`` and ``CMakeCache.txt``? Which Mapcrafter and gcc/clang versions are you using?

Of course this line is in the CMakeLists.txt. ;)
There was just a problem that different compiler versions needed different flags to enable C++11 features, but I resolved that in a newer version in the branch by checking the available C++11 flags.
