### ISSUE TITLE
make error in FBReader open source

### ISSUE THREAD

**Issue by youngsingh** [mapcrafter/mapcrafter#126]
In file included from /home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:26:0,
                 from ../filesystem/ZLFSManager.h:27,
                 from ZLibrary.cpp:28:
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/shared_ptr.h:1:1: error: expected unqualified-id before ‘.’ token
In file included from ../filesystem/ZLFSManager.h:27:0,
                 from ZLibrary.cpp:28:
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:39:30: error: ‘weak_ptr’ was not declared in this scope
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:39:52: error: template argument 2 is invalid
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:39:52: error: template argument 4 is invalid
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:39:54: error: expected unqualified-id before ‘>’ token
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:84:2: error: ‘shared_ptr’ does not name a type
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:85:2: error: ‘shared_ptr’ does not name a type
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:86:2: error: ‘shared_ptr’ does not name a type
/home/harkirat/Downloads/FBReader-master/zlibrary/core/../../zlibrary/core/include/ZLFile.h:94:2: error: ‘shared_ptr’ does not name a type
In file included from ZLibrary.cpp:28:0:
../filesystem/ZLFSManager.h:64:10: error: ‘shared_ptr’ does not name a type

**Comment by m0r13** [comment]
This is the wrong repo you are reporting this to, isn't it?

**Comment by youngsingh** [comment]
Ya sorry... 😢
