### ISSUE TITLE
ER: More detailed output for mapcrafter_markers would be helpful/nice

### ISSUE THREAD

**Issue by r3v** [mapcrafter/mapcrafter#131]
The current output looks something like this:

    World '/Users/cls/.grid/server/region':
    (1/94) Region 5:0
    (2/94) Region 3:-2
    (3/94) Region 2:-3
    (4/94) Region 2:-2
    (5/94) Region 1:1
    (6/94) Region 1:0

This is great for seeing progress, but gives very little information on the markers it has found and/or generated. It would be nice to see which markers it has spotted for each region it is processing. Something like:

    (5/94) Region 1:1
        - Found [home] marker for "r3v's house" at 1573,-540,69

And then possibly a summary at the end, showing how many markers were found, in total.  Even better if it's broken down by category.

    Marker generation complete!
    15 markers found in 8 categories:
    [home]: 4 [village]: 3 
... etc.

I've been wanting this for a while, but running into #130 (The Case of the Missing Markers) has prompted me to file this.

**Comment by m0r13** [comment]
Sure, with Mapcrafter's logging facility this shouldn't be a problem to implement. I'll have a look at this.

**Comment by m0r13** [comment]
I added some more debug and informational messages to the ``mapcrafter_marker`` tool. With the ``-v`` flag you can enable informational and progress messages, with ``-vv`` you can additionally enable the debug messages.

**Comment by r3v** [comment]
That's excellent! This will make the logfile I generate have some actual useful information. Thanks!
