### ISSUE TITLE
Improve handling of missing worlds

### ISSUE THREAD

**Issue by bugmancx** [mapcrafter/mapcrafter#136]
Mapcrafter should be more graceful at how it handles missing worlds. A few scenarios:

1. User sets up a new world in render.conf but no world has yet been generated by the minecraft server:

2015-03-14 11:03:41 [ERROR] [default] World section 'world1':
2015-03-14 11:03:41 [ERROR] [default]  - Error: 'input_dir' must be an existing directory! '/home/user/minecraft/server/worlds/world1' does not exist!

This error should skip this world and anything else relating to this world, and move on to the next (if there are more than one worlds configured.)

2. User creates a new world on the server and creates the render.conf sections for the Nether/End, but nether the Nether, nor the End have been explored on the game map:

2015-03-14 11:07:08 [INFO] [default] Scanning worlds...
Error: Region directory "/home/user/minecraft/server/worlds/world1/DIM1/region" does not exist!
2015-03-14 11:07:09 [FATAL] [default] Unable to load world world1_end!

or:

2015-03-14 11:07:56 [INFO] [default] Scanning worlds...
Error: Region directory "/home/user/minecraft/server/worlds/world1/DIM-1/region" does not exist!
2015-03-14 11:07:56 [FATAL] [default] Unable to load world world1_nether!

By gracefully ignoring these errors rather than making the fatal, mapcrafter can generate the maps that it was able to encounter and ignore those that it wasn't. This means that when map users eventually find the Nether or The End, mapcrafter will begin generating those maps on the next run without the need to add the relevant configuration (or uncomment, or whatever you did to work around this.)

**Comment by thorerik** [comment]
It is strictly incorrect, and considering standard *NIX conventions, this is how other utilities behave, pointing to things that doesn't exist, is pointing to the wrong place etc. is bad practice and can cause unexpected behaviour.

Handling it as a Fatal is incorrect, it should be an error, but that's minor semantics.
