### ISSUE TITLE
Not rendering gravel

### ISSUE THREAD

**Issue by KoniBrunner** [mapcrafter/mapcrafter#146]
Installed 1.5.4 on Ubuntu with the Debian package. Everything is working very well. Except the fact, that gravel is not rendered. My streets made out of gravel look like black holes: mc.ardamecraft.ch/world

**Comment by m0r13** [comment]
Sorry, I just get a 404. Which version of Mapcrafter are you exactly using?

**Comment by lalligood** [comment]
Looks like he forgot a trailing slash...

This worked for me:
http://mc.ardamecraft.ch/world/#map_world/0/0/211/-216/64

--Lance

**Comment by m0r13** [comment]
Ah, I see. But at least some gravel is rendered. Seems that the not rendered gravel has some strange block data (which is not known by Mapcrafter and the Minecraft Wiki). I could make Mapcrafter ignore all data values of gravel, can you build the newest Mapcrafter version with the patch from source and verify that this works for you?

**Comment by KoniBrunner** [comment]
Cloned and compiled. Same result. Where do I find the patch?

**Comment by m0r13** [comment]
Sorry, I didn't fix it yet. Wait a minute.

**Comment by m0r13** [comment]
You can pull now, rebuild, and try to re-render (force-render the map)...

**Comment by KoniBrunner** [comment]
Pulled, rebuildet, deleted entire map directory, rendered. Still looks the same.

**Comment by KoniBrunner** [comment]
Sorry, sorry, sorry. The not rendered stuff is not gravel. It's mossy brick. Don't know why I was thinking it's gravel.

**Comment by KoniBrunner** [comment]
The visible one is mossy_stonebrick and the not visible one is mossy_brick. Looks both the same in minecraft??

**Comment by m0r13** [comment]
Okay, I think I got it now. There were indeed some not implemented block data variants ([Monster egg](http://minecraft.gamepedia.com/Monster_Egg), ``mossy_brick`` is one of them). It should work now, you can try it.

**Comment by KoniBrunner** [comment]
Works perfect. Many thanks.

**Comment by m0r13** [comment]
No problem, you are welcome! :)
