### ISSUE TITLE
Hoppers are not rendered

### ISSUE THREAD

**Issue by stevemarple** [mapcrafter/mapcrafter#154]
Hoppers are not rendered, there is no code to do so. I have added some code (f51d1ca09d74faf5160a545ffe8826a0f914095b) which uses the outside texture for all sides, even those which are seen from the inside. With the normal texture pack there is little difference between the inside and outside textures. If this is an acceptable interim fix I can send a pull request. If someone can point me in the direction of how to set the inside block textures correctly based on orientation I'll try to fix properly.

**Comment by stevemarple** [comment]
Despite having used and viewed this for several days I now see my fix wasn't as complete as I had thought. Revised in ef4ef23589d725550374b364837ae2eac9cfa9c7 which I believe correctly uses the inside and outside textures.

**Comment by m0r13** [comment]
Thanks for looking at the source code and doing some hacking :)

Could you please create a pull request so I can better merge your changes?
