### ISSUE TITLE
Diorite/Andesite not rendered in top-down render view

### ISSUE THREAD

**Issue by konimaru** [mapcrafter/mapcrafter#161]
example for diorite (mapcrafter 2.0):
![iso](https://cloud.githubusercontent.com/assets/7730972/9545436/610a891a-4d8a-11e5-9834-25cf8e574507.png)
![top](https://cloud.githubusercontent.com/assets/7730972/9545438/63a1b22a-4d8a-11e5-81d7-7166ffc44db9.png)

**Comment by m0r13** [comment]
Oh, seems that I forgot them. I added them in commit 7fe924c29a9c441e3412470edd2449a0cdb50bc1, If you built Mapcrafter from source, you can already test if that works, otherwise there will be probably another version soon with bugfixes.

**Comment by konimaru** [comment]
Will do. Report back later.

**Comment by konimaru** [comment]
OK, that fixed it. Thanks.
