### ISSUE TITLE
question re: block_mask

### ISSUE THREAD

**Issue by konimaru** [mapcrafter/mapcrafter#162]
Right now the only place where one can use **block_mask** is in the *world section*. Just wondering if the *map section* would be a better place for it?

I tried to render a particular world with and without water. This only works by defining two worlds. The trouble with the latter is that switching view (between them) in the browser resets the zoom level. Which is perfectly OK given that they are usually two different worlds. Currently I side step that issue by editing the configuration file and align the world names.

**Comment by m0r13** [comment]
The block mask configuration option is part of the world section as the block mask technically changes (like the world crop options) the world to a different one. It would be an unnecessary effort to implement it this way (the block mask / world crop options are implemented at world/region/chunk level) and would make a block masked / cropped world less reusable.

Handling worlds with just different block masks as the same world shouldn't be a problem. I will think about a solution. Until this you can do a small workaround: Modify the [mapcrafterui.js-file](https://github.com/mapcrafter/mapcrafter/blob/master/src/data/template/static/js/mapcrafterui.js#L299). Replace ``world`` by ``worldName`` and use the ``world_name`` option in the world sections.

**Comment by konimaru** [comment]
Thanks for that explanation. I can live with my workaround ATM.

**Comment by m0r13** [comment]
Okay, I will keep this open as a reminder that I might change this someday. :)

**Comment by theSignSaysDie** [comment]
I do not know how to use the block mask feature - every time i try it never really renders. Is the such thing as an example config file that demonstrates the uses of every property? If not, is there an example for how to use block_mask?

Here is my config:
output_dir = output

[world:myworld]
input_dir = worlds\Our_world-

[world:myworld_nether]
input_dir = worlds\Our_world-
dimension = nether

[world:myworld_xray]
input_dir = worlds\Our_world-
block_mask = 2 3

[global:map]
texture_size = 16
rotations = top-left bottom-right bottom-left top-right
world = myworld
render_leaves_transparent = false



[map:map_myworld_day]
name = Day
render_mode = daylight

[map:map_myworld_cave]
name = Cave
render_mode = cave

[map:map_myworld_top]
name = Top down
render_view = topdown
render_mode = daylight

[map:map_myworld_top_cave]
name = Top down Cave
render_view = topdown
render_mode = cave

[map:map_myworld_nether]
world = myworld_nether
name = Nether View
render_mode = cave

[map:map_myworld_xray]
world = myworld_xray
name = X-ray view
render_mode = cave


This is set to just remove grass and dirt - but I can't see anything.
The program returns no error messages after reading the config either.
Thank you for helping me.

**Comment by lalligood** [comment]
@theSignSaysDie, I feel your pain. I've never played with the block mask feature & therefore cannot offer any direct help, but I completely agree with your sentiment about the (lack of specific) mapcrafter documentation available. I'd love to be the one to take a crack on improving the usage of the various config file options on the website if I had a way to do it! (Would it be worth me spending the time to add content like this to the mapcrafter wiki on GitHub?)

**Comment by wraithan** [comment]
@lalligood most of the docs live in the docs/ folder in the repo, I'd assume you'd add docs there.

@theSignSaysDie http://docs.mapcrafter.org/builds/stable/configuration.html#world-options shows some example uses of `block_mask`. The default is to show all blocks. So anything you put into the `block_mask` must assume that. If you want something to be hidden, you need to put a `!` in front of it. In programming `!` tends to mean `not`. So `block_mask = !2-3` would say don't show block ids from 2 until 3. It could also be written as `block_mask = !2 !3` to say don't show block ids 2 and 3.

**Comment by m0r13** [comment]
@lalligood  Of course there is plenty of documentation available at docs.mapcrafter.org. If there is something that you don't understand or that is described too complicated, don't be afraid to ask, I'm glad if I can help you. You are also free to submit a pull request if you want to make an improvement to the documentation (in the docs/ directory).

@theSignSaysDie The block mask is one of the more advanced features, that's why it's maybe not that easy to understand. It works about like @wraithan described it, please also have a look at the documentation part that he pointed out.

**Comment by lalligood** [comment]
Thank you @m0r13 & @theSignSaysDie. I'm going to take you up on that offer :-)
I remember that I spent a lot longer than I felt I should have (lots of trial & error) when I started using mapcrafter before I got it to run through successfully the first time. And now that I have a config that works, I'm generally inclined against making changes! I'll start with writing up some docs to help get newbies up & running faster & wade into the deeper stuff after that...

**Comment by m0r13** [comment]
@lalligood http://docs.mapcrafter.org/builds/stable/configuration.html Did you read this? It starts with a very basic example config...

**Comment by theSignSaysDie** [comment]
I did. It did not help, since i copied the example and got nothing.

**Comment by lalligood** [comment]
I don't recall the exact issues I ran into originally, but I'm inclined to agree with @theSignSaysDie's experience. It took quite a bit of trial & error & paying close attention to the error messages--which were actually useful!

**Comment by m0r13** [comment]
It did nothing? Did Mapcrafter throw any errors? There was no output? I tested this example and it *should* work, but if there is anything wrong with it, I would be glad if we can fix this.

**Comment by m0r13** [comment]
Also can you please create a new issue for this whole documentation thing? This issue is actually about another topic.

**Comment by wraithan** [comment]
`block_mask` has worked fine for me, I have ran many different exclusions and inclusions and they worked exactly as I expected and is documented. My only trouble was the same as the OP in this thread, I put it in the map block, not the world block, once I corrected that, everything worked.

**Comment by konimaru** [comment]
FWIW, I never had any trouble after I figured out that it:s a world-only option (indicated by warning message).

@theSignSaysDie; as for **block_mask = 2 3**, imagine a pool with all blocks included. During processing all **!n** expressions are removed everything **m** is added. In your case you add (2 3) to what:s already there (everything) so you don't see a change. When you only want those two IDs to be rendered you need **block_mask = !* 2 3**, i.e. remove all and add 2 and 3 again.

**Comment by theSignSaysDie** [comment]
It worked! thank you so much for this!
for the purposes of examples, here is my config.
I'll highlight the important parts.

output_dir = output

[world:myworld]
input_dir = worlds\Our_world-

[world:myworld_nether]
input_dir = worlds\Our_world-
dimension = nether

[world:myworld_xray]
input_dir = worlds\Our_world-
block_mask = !* 2-3

[global:map]
texture_size = 16
rotations = top-left bottom-right bottom-left top-right
world = myworld
render_leaves_transparent = false



[map:map_myworld_day]
name = Day
render_mode = daylight

[map:map_myworld_xray]
name = X-ray View
world = myworld_xray

[map:map_myworld_top]
name = Top down
render_view = topdown
render_mode = daylight

[map:map_myworld_top_cave]
name = Top down Cave
render_view = topdown
render_mode = cave

[map:map_myworld_nether]
world = myworld_nether
name = Nether View
render_mode = cave

Hope this is helpful!

**Comment by WORMSS** [comment]
I have to agree with the above, the fact that the block_mask is on the [world] and not the [map] makes things horrible with the view switching since it's a different world being selected. It means going between a world that is fully rendered, and then a world that has very specific mask rendering impossible as they both reset back to default_view.
