### ISSUE TITLE
slime overlay incorrect (rev 2.0)

### ISSUE THREAD

**Issue by konimaru** [mapcrafter/mapcrafter#163]
The screenshot shows a dedicated slime collection structure (underwater cobblestone cage). It's not marked as being a slime chunk. For comparison the chunk base output (red mark).

![screenshot](https://cloud.githubusercontent.com/assets/7730972/9580112/a8fcbf44-4ff7-11e5-951c-2311410fafee.png)
![slime_24101970](https://cloud.githubusercontent.com/assets/7730972/9580179/259ec83a-4ff8-11e5-94c0-fb85ca2b19a2.png)

**Comment by m0r13** [comment]
You aren't using a 32-bit platform? I think there were some issues with the Java random number generator I implemented.

Aside from that, I think that those online-javascript-slime-viewer might have some issues too. I compared Mapcrafters and Minecraft Overviewers slime chunk implementations with two online slime chunk viewers (I think the one you are showing and another one) and with a small Java program I wrote which generates slime chunks according to the slime chunk formula in the Minecraft wiki. All those programs had the same results for "small chunk coordinates" (I tested x, z < 100 I think). When I used larger coordinates (like the ones in your screenshot), only Mapcrafter, Minecraft Overviewer, and that Java program resulted in the same slime chunks. That makes me think that those online viewers have some overflow bugs. Is there some Java Minecraft mod that you could test?

**Comment by konimaru** [comment]
The vanilla client (no mods) I'm using brings its own Java 1.8.0_25 64bit version (on a 64bit platform). The slime coordinates (in fact any result from chunk base has been proven correct so far). IOW in that chunk I **do** get slime mobs whereas your overlay suggests I would not (they can't wander in as it's surrounded by water).

That said, lower coordinate areas show correct slime chunks in the overlay.

**Comment by m0r13** [comment]
Okay weird. Can you still test your slime chunks with some sort of slime chunk mod? I will have a look at the *ahem* Minecraft source to check if that slime formula is still correct. Maybe there is also something wrong with my random number generation...

**Comment by konimaru** [comment]
Will do. May take some time though (family & Co).

**Comment by konimaru** [comment]
map after update

![screenshot](https://cloud.githubusercontent.com/assets/7730972/9603524/795bd666-50b1-11e5-90b2-e75f06c9852f.png)

**Comment by m0r13** [comment]
Great, thanks for your pull request. #165
