### ISSUE TITLE
rendering issue iso vs topdown (rev 2.0, Ubuntu)

### ISSUE THREAD

**Issue by konimaru** [mapcrafter/mapcrafter#166]
AFAICT this only happens under Ubuntu (installation according to wiki). The latest windows build (mapcrafter_2.0~9~g16134c7_win64) and a compiled-from-source under Fedora don't have this issue. Basically, grass isn't properly rendered in topdown mode. That said, a friend of mine also has issues with sand (probably related).

![iso](https://cloud.githubusercontent.com/assets/7730972/9701339/7aed32c4-5424-11e5-9a0b-f3e9d6b6aabe.png)
![top](https://cloud.githubusercontent.com/assets/7730972/9701340/7d554510-5424-11e5-8744-9ba664aafcd2.png)

**Comment by m0r13** [comment]
Hmm. Seems like the grass block are not recognized as grass blocks. The dirt under it is rendered but black because of the lighting render mode. Can you recognize this by using the ``render_unknown_blocks = true`` option in your map section? Unknown blocks (the grass) should be red then.

**Comment by konimaru** [comment]
No such luck. They remain black. In this particular world gravel seems to be missing as well.

Are you saying that iso mode uses a different logic recognising blocks?

**Comment by m0r13** [comment]
Well let's say they don't use a different "logic", but it's a different implementation of the rendered blocks. So I have to implement how every block looks like twice - for the 3D and the 2D render mode.

Oh that's weird. Maybe it's an issue with the lighting render mode then. I see that only the transparent blocks are visible (transparent and non-transparent blocks like dirt have a slightly different lighting). Can you try to use the ``plain`` render mode?

Also does your whole world have this problem or just a few chunks?

**Comment by konimaru** [comment]
In plain render mode I **do** see all the previously missing blocks. And yes, the whole world is affected but I've seen artefacts (different world) in that about a chunk worth of sand was rendered in a desert which remained otherwise black.

**Comment by m0r13** [comment]
Okay then this looks like #87 and the problem I had with Windows builds in the beginning. Seems to be a very weird compiler bug. I'll try to reproduce the problem and debug it.

**Comment by konimaru** [comment]
Using **clang** (3.4) as the compiler works for me under Xubuntu. I just had to manually edit the **link.txt** files for it to get through the linker stage (**-lstdc++**). So far everything is green and **gravel**y (IOW as expected).

If you need help tracking this down just let me know.

**Comment by konimaru** [comment]
One thing - which always existed - is this border colouring artefact. If it's a side effect and gets resolved fine otherwise we may need an extra issue.

![border](https://cloud.githubusercontent.com/assets/7730972/9704403/ca3baadc-54a5-11e5-8087-75268888e485.png)

**Comment by m0r13** [comment]
Border coloring artefact? That's the normal lighting render mode, look how it looks like in the isometric render view, it's exactly the same thing just topdown. I added this to the topdown render view because otherwise you don't be able to recognize the structure of your world, everything would just look flat. If you don't like that, don't worry, I'm also thinking about a cartographic render mode which has some kind of height lines like a real map.

**Comment by konimaru** [comment]
OK, I'll check. If it's intended then it's probably fine :)

**Comment by konimaru** [comment]
NG
- gcc 4.7.2 (Debian), i486-linux-gnu, 32bit

OK
- clang 3.4 (Xubuntu), 32bit

**Comment by m0r13** [comment]
Hmm, with which Debian/Ubuntu package (which Debian/Ubuntu version?) does this happen exactly? I'm trying to reproduce the problem in a chroot environment. The package for Debian Wheezy 64 Bit seems to work.

**Comment by konimaru** [comment]
```
Linux kuroneko 3.2.0-4-486 #1 Debian 3.2.68-1+deb7u3 i686 GNU/Linux
```
Basically a VM running 32bit linux. I suspect the issue is the compiler.

What I see here is that normally a 2x2 grass spot has 4 draw calls (smooth). When it goes wrong somehow all block images seem to be transparent (at least one pixel) which forces 4x64 (all y levels down to 0) to be rendered. The top block in each group is grass but due to it being transparent it continues with the next block one below etc.

This suggests that image loading has a potential issue or some colour conversion is off.

**Comment by m0r13** [comment]
Thanks for the debugging you already did. Now I was able to reproduce the problem too. Weirdly it's only the topdown render mode, thought if transparency of blocks is an issue then both render views are broken... But how knows, now I can have a look at it too.

**Comment by konimaru** [comment]
Oddly enough iso mode is fine (just verified again). And noticed that the iso transparency check is more relaxed (< 250). If I change the topdown version to the same value I get my 2x2 green blocks.

**Comment by m0r13** [comment]
I was able to find out what caused the problem. The bilinear image scaling algorithm caused some slightly transparent pixels in the texture images that were read. I added a check for non-transparent pixels to prevent this. That's why blocks where detected as transparent in the topdown render view and things didn't work. It did work in the isometric render view because the transparency threshold there wasn't that strict.

Can you try the fix and confirm that it works?

**Comment by m0r13** [comment]
Damn I just recognized I pushed this to the wrong branch, you can still test it there, I'll merge that one too soon.

**Comment by konimaru** [comment]
So far so good. I hope it also resolves the issues my friend is having. I'll report back.

**Comment by konimaru** [comment]
Confirmed fixed. This can be closed now. Thanks.
