### ISSUE TITLE
[Question] What does this do, specifically?

### ISSUE THREAD

**Issue by Crayder** [mapcrafter/mapcrafter#168]
I need a cube streamer that doesn't stream the inside objects, only the objects that would be visible to a player. Would this help with that?

**Comment by m0r13** [comment]
I'm not sure what exactly you mean.

Mapcrafter renders your Minecraft worlds to a map (some static html files and images) viewable in any webbrowser. There are a lot of things you can configure (type of render view, rotations of your world, different render modes light day/night...).

Please have a look at the documentation: http://docs.mapcrafter.org
If you have further questions, you are free to join us in the #mapcrafter irc channel on freenode. :)
