### ISSUE TITLE
Jack o'Lantern/pumpkins not rendered correctly in iso mode

### ISSUE THREAD

**Issue by konimaru** [mapcrafter/mapcrafter#170]
For lighting purposes I sometimes group 4 blocks together facing inside (don't like being stared at). IOW I don't expect to see a carved face while viewing from different angles (below, NORTH is bottom right).

![screenshot](https://cloud.githubusercontent.com/assets/7730972/9758548/9d4f4a26-56e7-11e5-9bfe-3e8700f9ec7f.png)

**Comment by konimaru** [comment]
Fixed with cf34a7ede698863378519ee7d10b5560a076f72d and confirmed working.

**Comment by m0r13** [comment]
Okay thanks, can you create a PR for this so it's easier for me to merge?
