### ISSUE TITLE
Some config options not working

### ISSUE THREAD

**Issue by theSignSaysDie** [mapcrafter/mapcrafter#175]
I cannot make use of the options 'dimension' and 'block_mask' in the config files. Mapcrafter does not recognize them. I have version 2.0 (2.0~9~g16134c7)

**Comment by wraithan** [comment]
I was just using those with 2.0 as well as 2.1. You should share the error message you get when you try to run it. Also sharing your full config file would help debug as well.

**Comment by theSignSaysDie** [comment]
config file - render.conf
in its entirety
output_dir = output

[world:myworld]
input_dir = worlds\Our_world-
[global:map]
texture_size = 16
rotations = top-left bottom-right bottom-left top-right
world = myworld
render_leaves_transparent = false

[map:map_myworld_day]
name = Day
render_mode = daylight

[map:map_myworld_night]
name = Night
render_mode = nightlight

[map:map_myworld_top]
name = Top down
render_view = topdown
render_mode = daylight

[map:map_myworld_top_cave]
name = Top down Cave
render_view = topdown
render_mode = cave

[map:map_myworld_transparent]
name = X-ray vision
render_view = topdown
render_mode = cave
block_mask = !* 15-16 73 56 14 129 54 52


error msg:
2015-09-21 15:14:47 [WARNING] [default] There is a problem parsing the configuration file:
2015-09-21 15:14:47 [WARNING] [default] Map section 'map_myworld_transparent':
2015-09-21 15:14:47 [WARNING] [default]  - Warning: Unknown configuration option 'block_mask'!
2015-09-21 15:14:47 [WARNING] [default] Please have a look at the documentation.

**Comment by wraithan** [comment]
`block_mask` and `dimension` are world options, you'll want to create a new `[world:<name>]` for each `block_mask` and/or `dimension` you want.

**Comment by theSignSaysDie** [comment]
Thank you so much for this clarification!
