### ISSUE TITLE
Timeout when trying to reach mapcrafter.org repository through IPv6

### ISSUE THREAD

**Issue by dachande** [mapcrafter/mapcrafter#177]
I know, this is not a problem with your code, but when I recently tried to update my package list using apt I got a timeout while trying to get updates from mapcrafter.org through IPv6. Using IPv4 works fine though.

Maybe there is a misconfiguration in your IPv6 config.

**Comment by theSignSaysDie** [comment]
No problems on my end. Hope it gets better tho.

**Comment by dachande** [comment]
Works again.
