### ISSUE TITLE
Integer overflow causes circular crop to fail on large maps.

### ISSUE THREAD

**Issue by hujackus** [mapcrafter/mapcrafter#179]
Circular cropping fails on maps with blocks further than 46340 from the origin. No matter what radius is specified, extra blocks will be rendered well outside of the circular bounds. This is caused by an integer overflow found in a few methods of mapcraftercore/mc/worldcrop.cpp.

Example:
	bool WorldCrop::isBlockContainedXZ(const mc::BlockPos& block) const {
		if (type == RECTANGULAR) {
			// rectangular crop:
			// just check if the chunk is contained in the bounds
			return bounds_x.contains(block.x) && bounds_z.contains(block.z);
		} else if (type == CIRCULAR) {
			// circular crop:
			// also check distance to the center (like with regions and chunks)
			int dx = block.x - center.x;
			int dz = block.z - center.z;
			return radius*radius >= dx*dx + dz*dz;
		}
		return true;
	}

The integer overflow occurs in the dx*dx + dz*dz part. A simple fix would be to use long for the temporary calculations...

		long dx = block.x - center.x;
		long dz = block.z - center.z;
		return radius*radius >= dx*dx + dz*dz;

Methods that include this bug are:
WorldCrop::isRegionContained
WorldCrop::isChunkContained
WorldCrop::isBlockContainedXZ

**Comment by m0r13** [comment]
Hehe, you are already using Mapcrafter to it's limits. ;)

Would you like to fix this on your own (and confirm that it works) and then create a PR, or should I fix it?

**Comment by lalligood** [comment]
I've *got* to ask: Is there any way we could see your map? I thought mine was a decent size at +/-10,000 X & Z, but 45,000+...! O_O

**Comment by hujackus** [comment]
I think I will attempt to build the project from source at some point since I will likely break many things on my way to the far lands. However, until that happens I won't be able to commit anything myself.

As for seeing the map, it's being worked on. But you can imagine what it looks like, a jittery line that goes 1,255,000 blocks (so far) to the west. I have some pictures on twitter.com/hujackus.
