### ISSUE TITLE
Blocks not rendered perspectively correct

### ISSUE THREAD

**Issue by FrankyBoy** [mapcrafter/mapcrafter#181]
Hi!

Just started using your tool and noticed that the blocks are not rendered perspectively correct. Here's a comparison of how the blocks are currently rendered vs how they should be rendered:

http://i.imgur.com/F61qIqK.png

Left: current version, red and blue have same number of pixels (12 each).  
Right: perspectively correct version: blue is 12px, red is 16px

**Comment by hujackus** [comment]
Technically, red should be 13.8564px if blue is 12px, but that is impractical because (12 * 2tan 30) is an irrational number. It's a matter of taste, and 12px each is actually less incorrect.

**Comment by FrankyBoy** [comment]
No, 13.8... is just the length of the two-dimensional line, but that does not take into account the depth axis (though I am not sure what the exact value is). I made the same mistake when I first calculated around but when you draw a block with 14px high it still looks very flat. 

Really, the best way is just drawing blocks until it looks right, I'll add another pic with the different height values from 12 to 16 in a minute.

**Comment by m0r13** [comment]
Great... can't unsee now anymore! :-1: 

Just kidding. I never really thought about that. I like the way how it looks like, and it seems fine to me. I oriented myself by the way how Minecraft Overviewer and pigmap do the isometric rendering (they do it the same way) when I first wrote this part of the renderer. Also I wanted to keep things simple in the beginning and not mess around with arbitrary affine image transformations.

I'm afraid I won't change this is in the isometric renderer. It would break compatibility with older rendered maps and would make things a lot more complicated (I think, the block images are not quadratic then anymore...).

The good thing is that with the newer versions of Mapcrafter it's possible to write other renderers for the backend. So if someone with a bit more 3D knowledge would like to write a renderer that can render your maps *correctly* from an user defined perspective, he/she would be welcome. :)

**Comment by FrankyBoy** [comment]
\*evil laughter\*

Yes, it would make your tiles not quadratic, but the offset between your tiles (eg when stacking) is already not based on that anyhow (because you have overlap) -> don't see that making anything much worse.

sadly my c++ foo is non existent or I'd have a go. BTW, is there some build setup guide?

**Comment by m0r13** [comment]
I'll close this for now. Mapcrafter can render more perspectives with version for Minecraft 1.13 with much less programming effort, but one of the main assumptions is still that block images fit exactly on top of each over in a "row of viewing". Everything else would make choosing which block to render where *much* more complicated.
