### ISSUE TITLE
compiling with newest boost failed

### ISSUE THREAD

**Issue by atwebm** [mapcrafter/mapcrafter#182]
Hello,

After upgrading Boost to the newest Version 1.59.0-2 in my ArchLinux, it is impossible to compile mapcrafter from the git-repo.

The recompile is necessary because of an updated libboost_program_options.so

Scanning dependencies of target mapcrafter_markers
[ 75%] Building CXX object src/CMakeFiles/mapcrafter_markers.dir/mapcrafter_markers.cpp.o
In file included from /tmp/yaourt-tmp-markus/aur-mapcrafter-git/src/mapcrafter-git/src/mapcrafter_markers.cpp:20:0:
/tmp/yaourt-tmp-markus/aur-mapcrafter-git/src/mapcrafter-git/src/accumulator.h: In instantiation of 'accumulator_type<T>* accumulator(T*) [with T = int]':
/tmp/yaourt-tmp-markus/aur-mapcrafter-git/src/mapcrafter-git/src/mapcrafter_markers.cpp:164:44:   required from here
/tmp/yaourt-tmp-markus/aur-mapcrafter-git/src/mapcrafter-git/src/accumulator.h:97:41: error: invalid new-expression of abstract class type 'accumulator_type<int>'
     return new accumulator_type<T>(store);
                                         ^
/tmp/yaourt-tmp-markus/aur-mapcrafter-git/src/mapcrafter-git/src/accumulator.h:18:7: note:   because the following virtual functions are pure within 'accumulator_type<int>':
 class accumulator_type : public boost::program_options::value_semantic
       ^
In file included from /tmp/yaourt-tmp-markus/aur-mapcrafter-git/src/mapcrafter-git/src/accumulator.h:10:0,
                 from /tmp/yaourt-tmp-markus/aur-mapcrafter-git/src/mapcrafter-git/src/mapcrafter_markers.cpp:20:
/usr/include/boost/program_options/value_semantic.hpp:44:22: note:      virtual bool boost::program_options::value_semantic::adjacent_tokens_only() const
         virtual bool adjacent_tokens_only() const = 0;
                      ^
src/CMakeFiles/mapcrafter_markers.dir/build.make:62: recipe for target 'src/CMakeFiles/mapcrafter_markers.dir/mapcrafter_markers.cpp.o' failed
make[2]: *** [src/CMakeFiles/mapcrafter_markers.dir/mapcrafter_markers.cpp.o] Error 1
CMakeFiles/Makefile2:205: recipe for target 'src/CMakeFiles/mapcrafter_markers.dir/all' failed
make[1]: *** [src/CMakeFiles/mapcrafter_markers.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Enverex** [comment]
Ditto here.

	[ 87%] Built target mapcraftertest
	[ 88%] Building CXX object src/test/CMakeFiles/test_all.dir/test_misc.cpp.o
	[ 89%] Building CXX object src/test/CMakeFiles/test_all.dir/test_nbt.cpp.o
	[ 90%] Building CXX object src/test/CMakeFiles/test_all.dir/test_pos.cpp.o
	/tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/test/test_image_quantization.cpp: In member function 'void image_quantization_octree::test_method()':
	/tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/test/test_image_quantization.cpp:135:39: error: 'BOOST_MESSAGE' was not declared in this scope
	  BOOST_MESSAGE("Testing random image.");
										   ^
	src/test/CMakeFiles/test_all.dir/build.make:134: recipe for target 'src/test/CMakeFiles/test_all.dir/test_image_quantization.cpp.o' failed
	make[2]: *** [src/test/CMakeFiles/test_all.dir/test_image_quantization.cpp.o] Error 1
	make[2]: *** Waiting for unfinished jobs....
	/tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/test/test_nbt.cpp: In member function 'void nbt_testIO::test_method()':
	/tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/test/test_nbt.cpp:43:209: error: 'BOOST_MESSAGE' was not declared in this scope
	   BOOST_MESSAGE(std::string("Testing NBT with") + (compression == nbt::Compression::NO_COMPRESSION ? "out compression." : (compression == nbt::Compression::GZIP ? " Gzip compression." : " Zlib compression.")));
																																																					 ^
	In file included from /tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/mapcrafter_markers.cpp:20:0:
	/tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/accumulator.h: In instantiation of 'accumulator_type<T>* accumulator(T*) [with T = int]':
	/tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/mapcrafter_markers.cpp:164:44:   required from here
	/tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/accumulator.h:97:41: error: invalid new-expression of abstract class type 'accumulator_type<int>'
		 return new accumulator_type<T>(store);
											 ^
	/tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/accumulator.h:18:7: note:   because the following virtual functions are pure within 'accumulator_type<int>':
	 class accumulator_type : public boost::program_options::value_semantic
		   ^
	In file included from /tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/accumulator.h:10:0,
					 from /tmp/yaourt-tmp-ben/aur-mapcrafter-git/src/mapcrafter-git/src/mapcrafter_markers.cpp:20:
	/usr/include/boost/program_options/value_semantic.hpp:44:22: note:      virtual bool boost::program_options::value_semantic::adjacent_tokens_only() const
			 virtual bool adjacent_tokens_only() const = 0;
						  ^
	src/test/CMakeFiles/test_all.dir/build.make:182: recipe for target 'src/test/CMakeFiles/test_all.dir/test_nbt.cpp.o' failed
	make[2]: *** [src/test/CMakeFiles/test_all.dir/test_nbt.cpp.o] Error 1
	src/CMakeFiles/mapcrafter_markers.dir/build.make:62: recipe for target 'src/CMakeFiles/mapcrafter_markers.dir/mapcrafter_markers.cpp.o' failed
	make[2]: *** [src/CMakeFiles/mapcrafter_markers.dir/mapcrafter_markers.cpp.o] Error 1
	CMakeFiles/Makefile2:205: recipe for target 'src/CMakeFiles/mapcrafter_markers.dir/all' failed
	make[1]: *** [src/CMakeFiles/mapcrafter_markers.dir/all] Error 2
	make[1]: *** Waiting for unfinished jobs....
	CMakeFiles/Makefile2:631: recipe for target 'src/test/CMakeFiles/test_all.dir/all' failed
	make[1]: *** [src/test/CMakeFiles/test_all.dir/all] Error 2
	[ 91%] Linking CXX executable testtextures
	[ 91%] Built target testtextures
	[ 92%] Linking CXX executable mapcrafter
	[ 92%] Built target mapcrafter
	Makefile:127: recipe for target 'all' failed

**Comment by m0r13** [comment]
I already had the problem too and I fixed it, but in the wrong branch I see now. I'll do that in the master branch soon.

**Comment by m0r13** [comment]
And it should be fixed now in the master branch. Can you build again and confirm this?

**Comment by Enverex** [comment]
Worked here, thanks!

**Comment by m0r13** [comment]
No problem, you are welcome! :)
