### ISSUE TITLE
Packges not available over IPv6

### ISSUE THREAD

**Issue by Zsub** [mapcrafter/mapcrafter#186]
`packages.mapcrafter.org` has an IPv6 address (`2a01:4f8:201:8174:73::1337`) but nginx just gives a "Welcome to Nginx" page, instead of real results when trying to `apt-get update`, which means the update fails. My guess is there is a mistake in a site config for nginx and it can be fixed to add `listen [2a01:4f8:201:8174:73::1337]` to the config file used by the IPv4 site.

**Comment by m0r13** [comment]
Hmm that's weird. The nginx site is of course configured to listen on the ipv6 socket too. Me and @thorerik also tested accessing it via ipv6 and it worked. Do you still have the problem?

**Comment by Zsub** [comment]
I'm sorry, I had bluntly replaced `vivid` with `wily`. Using the `vivid` repository works as expected.

**Comment by m0r13** [comment]
Well then it's still a bit weird that you got the "Welcome to Nginx" page, and not a 403/404 error.
