### ISSUE TITLE
libboost_iostreams compiling error on fresh ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by speedingdeer** [mapcrafter/mapcrafter#188]
I'm trying to build mapcrafter on ubuntu 14.04 LTS (fresh installation)

I'm getting:

[ 89%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/thread/impl/multithreading.cpp.o
Linking CXX shared library libmapcraftercore.so
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_iostreams.a(gzip.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_iostreams.a: error adding symbols: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/mapcraftercore/libmapcraftercore.so] Error 1
make[1]: *** [src/mapcraftercore/CMakeFiles/mapcraftercore.dir/all] Error 2
make: *** [all] Error 2

Have you ever meet something like this ?

**Comment by lalligood** [comment]
Why not install mapcrafter from PPA?

--Lance


On Tue, Nov 24, 2015 at 12:16 PM, Filip Wiśniewski <notifications@github.com

**Comment by speedingdeer** [comment]
Thanks lalligood for the advice. I had the mapcrafter installed from PPA. I worked just fine. Now I'm trying to build it myself to use it in some some side project.

**Comment by speedingdeer** [comment]
BTW seems that PPA links against a too recent version of GCC and not compatible with slightly older machines (like LTS)

**Comment by speedingdeer** [comment]
I've just built the version 2.1 from from releases tag. It went smoothly. There must be a "bug" in the master branch, perhaps the support for 14.04 is abandoned but I don't think it is if 14.04 is LTS.

**Comment by m0r13** [comment]
Hey,

I have seen this error before, but it was when one tried to link Mapcrafter statically with boost and boost wasn't compiled with the right flags. I guess you are not trying to do this. Which version of gcc are you using exactly? Can you please show the complete output of cmake and make? Delete CMakeCache.txt and CMakeFiles first. And can you have a look at the CMakeCache.txt file if there is a variable set to true that is starting with OPT_LINK_BOOST I think?

**Comment by m0r13** [comment]
According to the "PPA": There is no Mapcrafter PPA, it's a normal Debian/Ubuntu package repository. ;)
The packages for every Debian/Ubuntu version are built in an environment of the distribution version, that way Mapcrafter should run under this Debian/Ubuntu version. What is the exact error you are getting with the package?

**Comment by speedingdeer** [comment]
Hi,

The install from .deb work fine on ubuntu 14.04 (just to confirm). What I was trying to and what failed was to extract executables from .deb and run by hand. I'm getting 
libstdc++.so.6: version `GLIBCXX_3.4.20'
which doesn't happen after I upgrade gcc. Then it works just fine too.
Compiling from master branch I get:


Scanning dependencies of target version.cpp
[  1%] Built target version.cpp
Scanning dependencies of target mapcraftercore
[  3%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/version.cpp.o
[  4%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/configparser.cpp.o
[  6%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/configsection.cpp.o
[  7%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/iniconfig.cpp.o
[  9%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/loggingconfig.cpp.o
[ 10%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/mapcrafterconfig.cpp.o
[ 12%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/validation.cpp.o
[ 13%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/webconfig.cpp.o
[ 15%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/configsections/log.cpp.o
[ 16%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/configsections/map.cpp.o
[ 18%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/configsections/marker.cpp.o
[ 19%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/config/configsections/world.cpp.o
[ 21%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/mc/chunk.cpp.o
[ 22%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/mc/nbt.cpp.o
[ 24%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/mc/pos.cpp.o
[ 25%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/mc/region.cpp.o
[ 27%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/mc/world.cpp.o
[ 28%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/mc/worldcache.cpp.o
[ 30%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/mc/worldcrop.cpp.o
[ 31%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/mc/worldentities.cpp.o
[ 33%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/biomes.cpp.o
[ 34%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/blockimages.cpp.o
[ 36%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/blocktextures.cpp.o
[ 37%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/image.cpp.o
[ 39%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/manager.cpp.o
[ 40%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/rendermode.cpp.o
[ 42%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderview.cpp.o
[ 43%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/textureimage.cpp.o
[ 45%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/tileset.cpp.o
[ 46%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/tilerenderer.cpp.o
[ 48%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/tilerenderworker.cpp.o
[ 50%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/rendermodes/cave.cpp.o
[ 51%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/rendermodes/heightoverlay.cpp.o
[ 53%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/rendermodes/lighting.cpp.o
[ 54%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/rendermodes/overlay.cpp.o
[ 56%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/rendermodes/slimeoverlay.cpp.o
[ 57%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/rendermodes/spawnoverlay.cpp.o
[ 59%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/image/dithering.cpp.o
[ 60%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/image/palette.cpp.o
[ 62%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/image/quantization.cpp.o
[ 63%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/image/scaling.cpp.o
[ 65%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/isometric/blockimages.cpp.o
[ 66%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/isometric/rendermodes.cpp.o
[ 68%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/isometric/renderview.cpp.o
[ 69%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/isometric/tilerenderer.cpp.o
[ 71%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/isometric/tileset.cpp.o
[ 72%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/topdown/blockimages.cpp.o
[ 74%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/topdown/rendermodes.cpp.o
[ 75%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/topdown/renderview.cpp.o
[ 77%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/topdown/tilerenderer.cpp.o
[ 78%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/renderer/renderviews/topdown/tileset.cpp.o
[ 80%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/util/filesystem.cpp.o
[ 81%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/util/logging.cpp.o
/home/speedingdeer/code/tmp/mapcrafter/src/mapcraftercore/util/logging.cpp: In member function ‘virtual void mapcrafter::util::LogSyslogSink::sink(const mapcrafter::util::LogMessage&)’:
/home/speedingdeer/code/tmp/mapcrafter/src/mapcraftercore/util/logging.cpp:269:56: warning: format not a string literal and no format arguments [-Wformat-security]
    util::replaceAll(message.message, "%", "%%").c_str());
                                                        ^
[ 83%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/util/other.cpp.o
[ 84%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/util/progress.cpp.o
[ 86%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/util/terminal.cpp.o
[ 87%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/thread/impl/singlethread.cpp.o
[ 89%] Building CXX object src/mapcraftercore/CMakeFiles/mapcraftercore.dir/thread/impl/multithreading.cpp.o
Linking CXX shared library libmapcraftercore.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_iostreams.a(gzip.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_iostreams.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/mapcraftercore/libmapcraftercore.so] Error 1
make[1]: *** [src/mapcraftercore/CMakeFiles/mapcraftercore.dir/all] Error 2
make: *** [all] Error 2




which doesn't happen if I compile from release 2.1 source code.

**Comment by m0r13** [comment]
I still need the CMake output. Please also put the output in code tags, that makes it easier to read.
