### ISSUE TITLE
lava night time rendering not always correct

### ISSUE THREAD

**Issue by konimaru** [mapcrafter/mapcrafter#189]
See below, same mountain, same lava fall, different time. This is with v2.1 (linux/windows).

![screenshot](https://cloud.githubusercontent.com/assets/7730972/11400248/863e5ff2-938c-11e5-8540-f47487882f31.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/7730972/11400251/8c633722-938c-11e5-93de-47687589edae.png)

**Comment by m0r13** [comment]
That's not my faul. :P

Minecraft sometimes tends to generate incorrect lighting data which is fixed when you enter those errors. Mapcrafter is just using the lighting data and not calculating it itself, that's why it's quite fast to apply the lighting.

**Comment by konimaru** [comment]
OK, bad luck I guess. Overviewer looks dark here as well.

Speaking of bugs, I recently got a deep ocean **chunk** in what is otherwise cold taiga. Go figure!

**Comment by konimaru** [comment]
Easy fix, I simply re/placed the source lava block and now everything looks as it should.
