### ISSUE TITLE
Add display elevation data to top down view.

### ISSUE THREAD

**Issue by Benchwork** [mapcrafter/mapcrafter#191]
I would love to see an option to add the elevation data to the top down view. something like this 
http://data.webglearth.com/doc/webgl-earthch3.html

**Comment by m0r13** [comment]
There is already an issue for this (#174). Unfortunately it's not that trivial to implement in this case and I'm quite busy at the moment with other things, but it's on my list. :)

I will close this issue as it's a duplicate.
