### ISSUE TITLE
Possible fencepost error with top-down map

### ISSUE THREAD

**Issue by miiichael** [mapcrafter/mapcrafter#192]
Hello again,

It looks a lot like the top-down map fails to notice when X=496..511 (eastern-most chunks in each region?) needs re-rendering. Z=496..511 does appear to work fine though. Haven't yet checked X near 1024 or -512 though.

For an example, see http://minecraft.deegan.id.au/3dmap/#polytopia_top/0/9/503/601/64 where I've recently been doing some railway realignment work...

**Comment by m0r13** [comment]
Do you still have the problem / did you try to just re-render your map? Maybe there are some funky problems with the chunk timestamps and/or the rendered image mtimes.
