### ISSUE TITLE
ISO C++ 2011 problem with building on ubuntu15.10 

### ISSUE THREAD

**Issue by DesmondTMB** [mapcrafter/mapcrafter#193]
I am trying to build mapcrafter on ubuntu15.10 with gcc 5.2.1 and get this error:
>  /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

I saw that this was an issue earlier, but that it was supposed to be fixed. I tried replacing all instances of '-std=c++0x' with '-std=c++11' in src/ but that did not do.
Attached is the complete output of 'make'  (called it *.txt, because git wanted me to).

[make.log.txt](https://github.com/mapcrafter/mapcrafter/files/53698/make.log.txt)

**Comment by m0r13** [comment]
Oh that's weird. The CMake files should try whether the C++11 flag of your compiler is "c++0x" or "c++11" and then use the supported one. Can you run CMake again and show me the output too (delete CMakeFiles/ and CMakeCache.txt first).

**Comment by DesmondTMB** [comment]
I managed to install it from the ppa in the meantime and am really impressed btw. Wonderful piece of software and the design with the config files is beautiful. Going to be able to have nice and up to date maps on my server, while I have to do no work after the initial setup. Thanks for that.

Here is the output of 'cmake'
```
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_NULLPTR
-- Performing Test HAVE_NULLPTR - Success
-- Performing Test HAVE_ENUM_CLASS_COMPARISON
-- Performing Test HAVE_ENUM_CLASS_COMPARISON - Success
-- Performing Test HAVE_ENUM_CLASS_FORWARD_DECLARATION
-- Performing Test HAVE_ENUM_CLASS_FORWARD_DECLARATION - Success
-- Looking for include file endian.h
-- Looking for include file endian.h - found
-- Looking for include file sys/endian.h
-- Looking for include file sys/endian.h - not found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Performing Test HAVE_ENDIAN_CONVERSION
-- Performing Test HAVE_ENDIAN_CONVERSION - Success
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.2)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/desmond/gitclones/mapcrafter/src
```

**Comment by m0r13** [comment]
Hehe. Your problem is that you ran CMake in the `mapcrafter/src/` directory, but you have to run it in `mapcrafter/`.

**Comment by DesmondTMB** [comment]
Oh okay.
Since I installed it through ppa already, I wont test it until I need it, but thanks. I'm notoriously bad in building from source. :)
