### ISSUE TITLE
Exclude area in config file

### ISSUE THREAD

**Issue by Benchwork** [mapcrafter/mapcrafter#196]
I map a few different worlds, and I want to stop rendering one spot. is there anyway to do this?

eg. Exclude:(X:X),(Z:Z,),(Y,)
eg. Exclude:<500:600>,<400:-300>,<64>

**Comment by m0r13** [comment]
I guess that wouldn't be too hard to implement, but I'm sorry that I have other things on my todo list first for this project and unfortunately I'm even more busy with other projects at the moment. 

Do you know that there is already a feature to render only a specified spot? If you want to hack it yourself, you could easily turn the "include only this spot" to "exclude this spot". ;) By the way, why would you want to exclude a certain area?

**Comment by Benchwork** [comment]
I'm willing to have a go at it, can you give me some pointers on where to look?  


As to the why, I want to work on an area near another users area, and surprise them, but others are still needing updates.

**Comment by m0r13** [comment]
There is the class `WorldCrop` ( https://github.com/mapcrafter/mapcrafter/blob/1e5df8c08f7d0e911d0af1cd313ade55a589a089/src/mapcraftercore/mc/worldcrop.h#L173 ), you can modify the `isXXXContained`-methods. Basically it should be just negating the return values, but maybe there are some special cases, I'm not sure right now. Just try it ;)

**Comment by m0r13** [comment]
I'm afraid there is no use-case for many users for this feature yet, that's why I'll close this feature request for now.
