### ISSUE TITLE
Adding Biomes o Plenty support

### ISSUE THREAD

**Issue by josephkimball** [mapcrafter/mapcrafter#197]
Hi m0r13,
I'd like to add support for Biomes o Plenty, and saw previous issue #32. In it you talk about a better way to add custom blocks. I was wondering if you could help me out and share that method, I know it's a lot of work but I'd like to put in the time to add all the blocks in BIomes o Plenty to mapcrafter.

Thanks!

**Comment by m0r13** [comment]
I wrote a bit about how block images are created in #217. That might be useful for you too if you want to implement additional blocks.

With that additional method to be better able to add blocks I meant some sort of configuration files for available blocks or even using the Minecraft block models, but that is and was just a rough idea. I don't have any further plans for that yet.

I would like to close this issue now, as I'm not planning to add Biomes o Plenty support in the near future. If you have questions about adding custom blocks, you are welcome in the other issue to ask. :)
