### ISSUE TITLE
Grass paths not being rendered

### ISSUE THREAD

**Issue by dbart** [mapcrafter/mapcrafter#201]
In 1.9, grass paths have been added to the PC version of Minecraft, but they are not being rendered correctly by mapcrafter. Maps just show black empty spaces where the paths are.

![grass-path-isometric](https://cloud.githubusercontent.com/assets/1301571/13500005/95cc9d86-e12e-11e5-8539-a1a2eccd59a2.png)
![grass-path-topdown](https://cloud.githubusercontent.com/assets/1301571/13500006/95d20c80-e12e-11e5-9992-74efeb2638bb.png)

**Comment by m0r13** [comment]
Hey, I didn't have the time yet to implement the new blocks, but I'll have a look at that soon. :)

**Comment by m0r13** [comment]
I got them implemented. :)
Other 1.9 blocks and a new version will follow soon.

![screen](https://cloud.githubusercontent.com/assets/1788152/13714568/a73f8d1a-e7cf-11e5-97da-c48387b69c40.png)

**Comment by m0r13** [comment]
Should be resolved with Mapcrafter 2.2.1. In case there are problems with the new blocks, please open a new issue.
