### ISSUE TITLE
Certificate error for package server, needs to be renewed

### ISSUE THREAD

**Issue by maiki** [mapcrafter/mapcrafter#215]
Wasn't sure if this should be in [mapcrafter/mapcrafter.org](https://github.com/mapcrafter/mapcrafter.org) or not, but as this project gets more issue traffic, here it goes.

The Debian/Ubuntu repo certificate is broken. Going to https://packages.mapcrafter.org/ serves the cert for avatars.mapcrafter.org, issued by Let's Encrypt. Likely an LE cert needs to be renewed.

Current error message:

```
Connecting to packages.mapcrafter.org (packages.mapcrafter.org)|148.251.55.244|:443... connected.
ERROR: cannot verify packages.mapcrafter.org's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
ERROR: no certificate subject alternative name matches
	requested host name ‘packages.mapcrafter.org’.
To connect to packages.mapcrafter.org insecurely, use `--no-check-certificate'.
```

Thanks for providing packages! ^_^

**Comment by m0r13** [comment]
I got the certificate just the day before yesterday. I'm still working on the whole SSL-setup and I see that I forgot the packages.mapcrafter.org alternative name, I'll have a look at it.

**Comment by m0r13** [comment]
Just added the alternative name and renewed the certificate. Don't wonder about the avatars.mapcrafter.org, I just forgot to specify a common name and it used the first alternative name, but that's fixed now too. A problem is still that wget can't verify the issuer's authority, I'll try to fix that too.

**Comment by m0r13** [comment]
Should be fixed now too, can you verify it?

**Comment by maiki** [comment]
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.mapcrafter.org wily Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B6F77E28FE4F4EAC

W: Failed to fetch http://packages.mapcrafter.org/ubuntu/dists/wily/Release  
```

Not working yet. But also, I am not that familiar with package caching in apt(-get), so maybe I need to clear something. I will poke around.

**Comment by m0r13** [comment]
Did you run the command to download the repository public key? Maybe you ran it but at that time the certificates didn't work, so you weren't able to download it. Here: ``sudo wget -O /etc/apt/trusted.gpg.d/mapcrafter.gpg http://packages.mapcrafter.org/debian/keyring.gpg``.

**Comment by maiki** [comment]
Yes, I did that and it worked. Good job! ^_^
