### ISSUE TITLE
Minecraft 1.9.2 Nether Rendering does not work

### ISSUE THREAD

**Issue by nethermapper1** [mapcrafter/mapcrafter#219]
I am unable to render a nether view with a world created with vanilla Minecraft 1.9.2.
I have tried the latest stable Mapcrafter version for ubuntu 14.04 and i have tried the current Mapcrafter version from github (2.2.1 (v.2.2.1-6-gd3af7f3)).
[mapcraft-nether.conf.txt](https://github.com/mapcrafter/mapcrafter/files/222628/mapcraft-nether.conf.txt)
When starting Mapcrafter with "mapcrafter -c mapcraft-nether.conf" i get the following error:
`[INFO] [default] Scanning worlds...`
`Error: Region directory "/home/username/minecraftbackup/testworld/DIM-1/region" does not exist! `
`[FATAL] [default] Unable to load world testworld!`

**Comment by thorerik** [comment]
If you haven't been to the nether, the region doesn't exist yet, additionally if your world is of an older type the path is different (though I can not remember what it is)

**Comment by nethermapper1** [comment]
The Minecraftworld was created by the minecraft-server. The servers initial setup was after the release of Minecraft 1.9.2 and i downloaded the minecraftserver.jar from minecraft.net.
I visited the nether multiple times.
This is my world directory:

/minecraftbackup/testworld/$ tree
.
├── playerdata
│   ├── dea0dcbb-b56d-46ff-a1af-bae5c7326d95.dat
│   └── faf82c9d-1cbd-4302-814d-8f2906fb4295.dat
└── region
    ├── r.0.1.mca
    ├── r.0.2.mca
    ├── r.0.-3.mca
    ├── r.0.-5.mca
    ├── r.1.0.mca
    ├── r.1.1.mca
    ├── r.1.-1.mca
    ├── r.-1.1.mca
    ├── r.1.2.mca
    ├── r.1.-2.mca                                                                                                                                                                           
    ├── r.-1.2.mca
    ├── r.-1.-2.mca
    ├── r.1.-3.mca
    ├── r.-1.-3.mca
    ├── r.1.-4.mca
    ├── r.-1.-4.mca
    ├── r.-1.-5.mca
    ├── r.-2.0.mca
    ├── r.-2.1.mca
    ├── r.-2.2.mca
    ├── r.2.-3.mca
    ├── r.-2.-3.mca
    └── r.3.-3.mca

2 directories, 25 files

**Comment by nethermapper1** [comment]
Nevermind my backup of my world has corrupted files.
