### ISSUE TITLE
Move map by dragging

### ISSUE THREAD

**Issue by mathuin** [mapcrafter/mapcrafter#225]
It would be nice to be able to move the map by clicking and holding the left mouse button, then moving the mouse pointer.  Right now I have to zoom out from one side then in on the other to scoot the map around.

**Comment by m0r13** [comment]
That is already an feature implemented by Leaflet. Have you tried different web browsers? Which browser(s) are you using? Maybe if you can't see any controls (zoom, map/rotation select etc.) but the map maybe something failed during the initialization. In that case an error output from the browser console would be helpful.

**Comment by mathuin** [comment]
Oh hey, forgot to close this.  I was unable to reproduce the problem.  My browser was Chrome, and at first it wouldn't move until after I clicked again on the screen, but then it just worked normally.  No error output, probably user error.  I apologize for opening the issue before asking on IRC. :-)
