### ISSUE TITLE
Maps miss align when using texture_size

### ISSUE THREAD

**Issue by sylcai** [mapcrafter/mapcrafter#228]
When using this config - the maps are no longer aligned by co-ordinates. Only the map that does not use smaller pixels for blocks is fine. The others are off kilter, no longer lining up during a view switch, and markers are not in the correct visual spot.

`output_dir = minecraft_map

[world:equanimity]
input_dir = worlds\equanimity
crop_unpopulated_chunks = true
crop_min_y = 4
crop_max_y = 254
crop_min_x = -1617
crop_max_x = 4738
crop_min_z = -4928
crop_max_z = 1472

[world:eq_nether]
input_dir = worlds\equanimity
dimension = nether
crop_unpopulated_chunks = true
crop_min_y = 30
crop_max_y = 120

[world:eq_end]
input_dir = worlds\equanimity
dimension = end
crop_unpopulated_chunks = true

[map:map_eq]
name = Overworld
world = equanimity
texture_dir = data/textures/johnsmith

[map:map_eq_chunks]
name = Chunk View
world = equanimity
render_view = topdown
render_mode = plain
texture_dir = data/textures/johnsmith
texture_size = 1
tile_width = 12
png_indexed = true

[map:map_eq_caves]
name = Overworld Caves
world = equanimity
render_mode = cave
texture_dir = data/textures/johnsmith
texture_size = 2
tile_width = 6
png_indexed = true

[map:map_eq_nether]
name = The Nether
world = eq_nether
render_mode = cave
texture_size = 2
tile_width = 6
png_indexed = true

[map:map_eq_end]
name = The End
world = eq_end
render_mode = nightlight
texture_dir = data/textures/johnsmith
texture_size = 3
tile_width = 4
png_indexed = true`

**Comment by sylcai** [comment]
After doing some additional research, it is the images that are in the wrong position. The markers still have the correct co-ords

**Comment by m0r13** [comment]
I know - this is a known issue, see #198. Unfortunately I wasn't able yet to fix it. Feel free to add your observations to the discussion of that issue. I would close this issue then as it is a duplicate.

**Comment by sylcai** [comment]
Sorry - I don't know yet how to use search for issues on github. Didn't intend to open duplicate.

**Comment by m0r13** [comment]
No problem :)

**Comment by m0r13** [comment]
@sylcai  can you test if it works for you now? I re-implemented the coordinate conversion for the topdown view and with my local test-worlds it fixed the problem. Please answer in the new issue. I wasn't able to notify you there, so I'm writing that here.
