### ISSUE TITLE
Update downloads to version 2.3.1

### ISSUE THREAD

**Issue by Yepoleb** [mapcrafter/mapcrafter#231]
The current downloads page and packages are still on 2.3.

**Comment by m0r13** [comment]
I know the ``VERSION`` file already says 2.3.1, but there was an bug which I wanted to fix first. Sorry I didn't find the time yet, I'm a bit busy with exams again.

**Comment by Yepoleb** [comment]
Which bug is it? If it's nothing critical I'll switch to the nightly builds until the new stable is released.

**Comment by m0r13** [comment]
Yes, you should be able to switch the nightly builds. The bug is a very specific lighting bug occuring only with Mapcrafter built by specific clang versions.

**Comment by m0r13** [comment]
Mapcrafter 2.3.1 packages are built now.
