### ISSUE TITLE
Map tiles (Leaflet) empty --> No Map output in html

### ISSUE THREAD

**Issue by davedlx** [mapcrafter/mapcrafter#234]
Hi Mapcrafter team,

So i've been using mapcrafter on different installations of ubuntu, but this one drives me crazy.
I tried reinstalling mapcrafter, chenged webservers, fiddled around with permissions (right now back to unsing apache2)... i'm out of ideas and my map ist still empty.

I've never faced this before on any other installation!

the mapcrafter html files are currently located on my ubtuntu 14.04 installation on [http://pitziminecraft.selfhost.eu/maps](http://pitziminecraft.selfhost.eu/maps)

what could be the issue?

output of mapcrafter:
dave@precision390:~$ mapcrafter -c render.conf -j 2
2016-08-31 14:58:29 [INFO] [default] Scanning worlds...
2016-08-31 14:58:30 [INFO] [default] [1/1] Rendering map map_world_day ("Normal World - Day"):
2016-08-31 14:58:30 [INFO] [default] [1.1/1.1] Rendering rotation top-left...
2016-08-31 14:58:30 [INFO] [default] Scanning required tiles...
[============================================] 100.00% 10051/10051 15.51/s
2016-08-31 15:09:18 [INFO] [default] [1.1/1.1] Rendering rotation top-left took 648 seconds.
2016-08-31 15:09:18 [INFO] [default] Rendering all worlds took 648 seconds.
2016-08-31 15:09:18 [INFO] [default] Finished.....aaand it's gone!
dave@precision390:~$

this is the tree of "world"

dave@precision390:~$ tree /var/games/minecraft/servers/Pitzionat_187/world
/var/games/minecraft/servers/Pitzionat_187/world
├── data
│   ├── Fortress.dat
│   ├── idcounts.dat
│   ├── map_0.dat
│   ├── map_10.dat
│   ├── map_11.dat
│   ├── map_12.dat
│   ├── map_13.dat
│   ├── map_14.dat
│   ├── map_15.dat
│   ├── map_16.dat
│   ├── map_17.dat
│   ├── map_18.dat
│   ├── map_19.dat
│   ├── map_1.dat
│   ├── map_20.dat
│   ├── map_21.dat
│   ├── map_22.dat
│   ├── map_23.dat
│   ├── map_24.dat
│   ├── map_25.dat
│   ├── map_26.dat
│   ├── map_27.dat
│   ├── map_28.dat
│   ├── map_29.dat
│   ├── map_2.dat
│   ├── map_30.dat
│   ├── map_31.dat
│   ├── map_32.dat
│   ├── map_33.dat
│   ├── map_34.dat
│   ├── map_35.dat
│   ├── map_36.dat
│   ├── map_37.dat
│   ├── map_38.dat
│   ├── map_39.dat
│   ├── map_3.dat
│   ├── map_40.dat
│   ├── map_41.dat
│   ├── map_42.dat
│   ├── map_43.dat
│   ├── map_44.dat
│   ├── map_45.dat
│   ├── map_46.dat
│   ├── map_47.dat
│   ├── map_48.dat
│   ├── map_49.dat
│   ├── map_4.dat
│   ├── map_50.dat
│   ├── map_51.dat
│   ├── map_52.dat
│   ├── map_53.dat
│   ├── map_54.dat
│   ├── map_55.dat
│   ├── map_56.dat
│   ├── map_57.dat
│   ├── map_58.dat
│   ├── map_59.dat
│   ├── map_5.dat
│   ├── map_60.dat
│   ├── map_61.dat
│   ├── map_62.dat
│   ├── map_63.dat
│   ├── map_64.dat
│   ├── map_65.dat
│   ├── map_66.dat
│   ├── map_67.dat
│   ├── map_68.dat
│   ├── map_69.dat
│   ├── map_6.dat
│   ├── map_70.dat
│   ├── map_71.dat
│   ├── map_72.dat
│   ├── map_73.dat
│   ├── map_74.dat
│   ├── map_75.dat
│   ├── map_76.dat
│   ├── map_77.dat
│   ├── map_78.dat
│   ├── map_79.dat
│   ├── map_7.dat
│   ├── map_80.dat
│   ├── map_81.dat
│   ├── map_8.dat
│   ├── map_9.dat
│   ├── Mineshaft.dat
│   ├── Monument.dat
│   ├── scoreboard.dat
│   ├── Stronghold.dat
│   ├── Temple.dat
│   ├── Village.dat
│   ├── villages.dat
│   ├── villages_end.dat
│   └── villages_nether.dat
├── DIM1
│   └── region
│       ├── r.0.0.mca
│       ├── r.0.-1.mca
│       ├── r.-1.0.mca
│       ├── r.-1.-1.mca
│       ├── r.-1.1.mca
│       ├── r.1.1.mca
│       ├── r.2.1.mca
│       └── r.2.2.mca
├── DIM-1
│   └── region
│       ├── entities.nbt.gz
│       ├── r.0.0.mca
│       ├── r.0.-1.mca
│       ├── r.-1.0.mca
│       └── r.-1.-1.mca
├── level.dat
├── level.dat_old
├── playerdata
│   ├── 0c876da9-c921-34b1-92ef-661c83085749.dat
│   ├── 0de630ce-6999-3d6d-967c-f96e4edc17ad.dat
│   ├── 1f8d0dbf-26c2-359c-80ce-d2f87d5bef63.dat
│   ├── 2154df7f-7f60-3e65-befa-286cc5c60887.dat
│   ├── 375fba13-940f-35cb-bca0-e9ad2aa4bed9.dat
│   ├── 39d9910e-eeba-33b9-8a51-57a3e8aadfd7.dat
│   ├── 3bce114d-e2d4-303a-85f9-381bedabfdec.dat
│   ├── 3fbfc2b5-7d90-39a8-a6ac-ab52ff3cd314.dat
│   ├── 46419f65-194a-38d0-bb7a-e12c47973207.dat
│   ├── 530fa97a-357f-3c19-94d3-0c5c65c18fe8.dat
│   ├── 6e441449-2027-3d5d-ab61-0919367636e7.dat
│   ├── 7240e2a2-3eb1-33a4-bde0-efba2a57f71c.dat
│   ├── 7b649ecc-1647-3bc5-9eb5-30dd5745a280.dat
│   ├── 80333097-598c-3d5f-9b99-4ef1a3920f06.dat
│   ├── 82d15b24-3b12-31dd-b118-68a78dfacd61.dat
│   ├── 8b8b7e65-a449-3620-bb38-409e4c4ffc29.dat
│   ├── 94472419-a8d5-30ea-ad3b-ff7771d790ec.dat
│   ├── 97e4714d-1539-31bb-9476-9f1bdeae85c9.dat
│   ├── 9da495c1-916b-3251-9f1b-edde09973f7c.dat
│   ├── a1dd14e1-4e26-3be3-acc5-8208d70c3706.dat
│   ├── a5381248-7f10-3a70-9f70-1e49706e0cbf.dat
│   ├── a9749f9e-8745-3eea-a993-fcc5d89bb5c5.dat
│   ├── c2583fbf-5ec9-3d18-b0b1-9b4ceaff58d6.dat
│   ├── c4081878-298b-3ceb-bc95-22f11d1b4c16.dat
│   ├── c422900b-b623-36fd-b2b4-772e0efe20c3.dat
│   ├── cca5351e-49d6-3ad9-8eb4-fca887700828.dat
│   ├── cf1cb268-f741-3608-b691-d7361a25bdd5.dat
│   ├── d3af25c8-0b86-3649-ac3b-c69f6418e54e.dat
│   ├── d9681d52-c26f-34bf-afc2-1d2b209e3522.dat
│   ├── db01a093-82e2-30fa-8a55-7853d64a4cbe.dat
│   ├── dc21854e-f7bb-3541-bada-17bc5d585935.dat
│   ├── ddcd9f78-1db2-39dc-9bac-e6a7ba578fd2.dat
│   ├── e2b27990-a670-377a-adc0-614c00f77137.dat
│   ├── e3a2f954-d993-3cb9-a7d8-e893f5c2f632.dat
│   ├── e7ee2b57-7c16-3971-948c-39cd7b1c5e0c.dat
│   ├── f4b1d43a-f3b2-3203-9cb9-1d1dcd25ca82.dat
│   └── fa2eaab1-2e86-32bd-bcd9-17a811eea623.dat
├── region
│   ├── entities.nbt.gz
│   ├── r.0.0.mca
│   ├── r.0.19.mca
│   ├── r.0.-1.mca
│   ├── r.0.1.mca
│   ├── r.0.-2.mca
│   ├── r.0.2.mca
│   ├── r.0.3.mca
│   ├── r.-1.0.mca
│   ├── r.1.0.mca
│   ├── r.-1.19.mca
│   ├── r.-1.-1.mca
│   ├── r.-1.1.mca
│   ├── r.1.-1.mca
│   ├── r.1.1.mca
│   ├── r.-1.-2.mca
│   ├── r.-1.2.mca
│   ├── r.1.-2.mca
│   ├── r.1.2.mca
│   ├── r.-1.3.mca
│   ├── r.1.3.mca
│   ├── r.-2.0.mca
│   ├── r.2.0.mca
│   ├── r.-2.-1.mca
│   ├── r.-2.1.mca
│   ├── r.2.-1.mca
│   ├── r.2.1.mca
│   ├── r.-2.-2.mca
│   ├── r.-2.2.mca
│   ├── r.2.-2.mca
│   ├── r.2.2.mca
│   ├── r.-2.3.mca
│   ├── r.2.3.mca
│   ├── r.-3.0.mca
│   ├── r.3.0.mca
│   ├── r.-3.-1.mca
│   ├── r.3.-1.mca
│   ├── r.3.1.mca
│   ├── r.-3.-2.mca
│   ├── r.3.-2.mca
│   ├── r.3.2.mca
│   ├── r.3.3.mca
│   ├── r.-4.0.mca
│   ├── r.4.0.mca
│   ├── r.-4.-1.mca
│   ├── r.-4.-2.mca
│   ├── r.-5.-1.mca
│   ├── r.-5.-2.mca
│   ├── r.58.58.mca
│   └── r.5859.5859.mca
├── session.lock
└── stats
    ├── 0c876da9-c921-34b1-92ef-661c83085749.json
    ├── 0de630ce-6999-3d6d-967c-f96e4edc17ad.json
    ├── 1f8d0dbf-26c2-359c-80ce-d2f87d5bef63.json
    ├── 2154df7f-7f60-3e65-befa-286cc5c60887.json
    ├── 375fba13-940f-35cb-bca0-e9ad2aa4bed9.json
    ├── 39d9910e-eeba-33b9-8a51-57a3e8aadfd7.json
    ├── 3bce114d-e2d4-303a-85f9-381bedabfdec.json
    ├── 3fbfc2b5-7d90-39a8-a6ac-ab52ff3cd314.json
    ├── 46419f65-194a-38d0-bb7a-e12c47973207.json
    ├── 530fa97a-357f-3c19-94d3-0c5c65c18fe8.json
    ├── 6e441449-2027-3d5d-ab61-0919367636e7.json
    ├── 7240e2a2-3eb1-33a4-bde0-efba2a57f71c.json
    ├── 7b649ecc-1647-3bc5-9eb5-30dd5745a280.json
    ├── 80333097-598c-3d5f-9b99-4ef1a3920f06.json
    ├── 82d15b24-3b12-31dd-b118-68a78dfacd61.json
    ├── 8b8b7e65-a449-3620-bb38-409e4c4ffc29.json
    ├── 94472419-a8d5-30ea-ad3b-ff7771d790ec.json
    ├── 97e4714d-1539-31bb-9476-9f1bdeae85c9.json
    ├── 9da495c1-916b-3251-9f1b-edde09973f7c.json
    ├── a1dd14e1-4e26-3be3-acc5-8208d70c3706.json
    ├── a5381248-7f10-3a70-9f70-1e49706e0cbf.json
    ├── a9749f9e-8745-3eea-a993-fcc5d89bb5c5.json
    ├── c2583fbf-5ec9-3d18-b0b1-9b4ceaff58d6.json
    ├── c4081878-298b-3ceb-bc95-22f11d1b4c16.json
    ├── c422900b-b623-36fd-b2b4-772e0efe20c3.json
    ├── cca5351e-49d6-3ad9-8eb4-fca887700828.json
    ├── cf1cb268-f741-3608-b691-d7361a25bdd5.json
    ├── d3af25c8-0b86-3649-ac3b-c69f6418e54e.json
    ├── d9681d52-c26f-34bf-afc2-1d2b209e3522.json
    ├── db01a093-82e2-30fa-8a55-7853d64a4cbe.json
    ├── dc21854e-f7bb-3541-bada-17bc5d585935.json
    ├── ddcd9f78-1db2-39dc-9bac-e6a7ba578fd2.json
    ├── e2b27990-a670-377a-adc0-614c00f77137.json
    ├── e3a2f954-d993-3cb9-a7d8-e893f5c2f632.json
    ├── e7ee2b57-7c16-3971-948c-39cd7b1c5e0c.json
    ├── f4b1d43a-f3b2-3203-9cb9-1d1dcd25ca82.json
    └── fa2eaab1-2e86-32bd-bcd9-17a811eea623.json

8 directories, 233 files

**Comment by m0r13** [comment]
Of course Mapcrafter rendered your map. The problem is just that you have a single region file that is very far out (probably just some randomly generated chunks by the server), all the other regions are located around the coordinate origin.

You have to zoom in quite a bit to find that coordinate origin with all your regions: http://pitziminecraft.selfhost.eu/maps/#map_world_day/0/16/288/64/64

A solution would be to delete/move the region file that is so far out (``r.5859.5859.mca``) or render only that little part of your world (https://docs.mapcrafter.org/builds/stable/configuration.html#world-options scroll a bit down to world cropping).
