### ISSUE TITLE
UI shows images of multiple levels at the same time

### ISSUE THREAD

**Issue by andregasser** [mapcrafter/mapcrafter#236]
Hi,

I run a 1.10.2 Minecraft server and have installed release 2.3.1 of Mapcrafter. Whenever I use the web viewer to watch the rendered map, I experience some kind of display glitch when zooming in and out of the map.
It looks like the UI shows image tiles of the wrong zoom level (see attached image, red rectangles). Is this a known problem or is something known to work around this issue? I experience this problem in multiple browsers.

Best regards,
André
![mapcrafter-display-glitch-2 3 1](https://cloud.githubusercontent.com/assets/535130/18631041/149320de-7e70-11e6-84f1-a9daddbf0b53.png)

**Comment by andregasser** [comment]
Ah by the way: You can go and check it out for yourself here: http://mapcrafter-survival.g2static.com/

Best regards,
André

**Comment by thorerik** [comment]
This is usually caused by worlds that grow and gaining another render level, you can resolve it by forcing a re-render.

**Comment by andregasser** [comment]
Hi Erik,

Thx for the feedback. I forgot to mention that I use JPG as image output format and a texture size of 16. After switching to indexed PNG with a default texture size of 12.I mostly did this in order to save disk space. Also, I did clear all temporary output folders and performed a full re-render, as suggested by you. Everything runs smooth again. 

Regards,
André
