### ISSUE TITLE
Ubuntu 16.04 Xenial Xerus & 16.10 YakketyYak

### ISSUE THREAD

**Issue by shmolf** [mapcrafter/mapcrafter#237]
This is a request/offer.
Is there anything I can do to help support a 16.04 and 16.10 .deb package?
If not, are there any plans for such a package?
Else, I can build from source.
Thank you

**Comment by rposborne** [comment]
I was able to install on 16.04 by using the apt packages. https://docs.mapcrafter.org/builds/stable/installation.html#debian-packages

**Comment by thorerik** [comment]
@m0r13 is already building xenial packages by the look of things:
https://buildbot.mapcrafter.org/builders/deb-ubuntu-xenial-amd64
16.10 packages should be a quick update of the buildbot as well as the build files:
https://github.com/mapcrafter/mapcrafter-buildfiles/blob/master/debian/control.sh#L43-L46

**Comment by shmolf** [comment]
Thank you. I installed using your instructions, and it worked great.
Corbindallas.ddns.net:2121

**Comment by thorerik** [comment]
Yakkety packages have now been added:
https://buildbot.mapcrafter.org/builders/deb-ubuntu-yakkety-amd64/builds/7

**Comment by thorerik** [comment]
scratch that, just tested on a docker box and see that it's failing due to repo issues. I've made @m0r13 aware of it on IRC, so hopefully we'll find a way to resolve those issues soon™

**Comment by shmolf** [comment]
10-4

**Comment by elamperti** [comment]
Closing this issue as it has more than 3 years now, and I'm seeing builds for Xenial and Bionic among the [nightly builds](https://mapcrafter.org/downloads/nightly). 

If current builds were not working for a specific Ubuntu version, please feel free to open a new issue. Thank you! :)


EDIT: I see that the package downloads are throwing a 403 error, as mentioned in #312. Let's follow that particular problem on said issue.
