### ISSUE TITLE
Uploading my map for the public.

### ISSUE THREAD

**Issue by XxArmaxX** [mapcrafter/mapcrafter#238]
Not sure if this is the place to post this, but how can I upload my map onto a website so that others can see it.

**Comment by Ferroin** [comment]
There's a couple of options.  The two easiest for sharing over the internet are probably:
1. Get a web hosting provider.
2. Create a ZIP archive of the map, upload it somewhere like Dropbox, and then share it to people that way.

There is also of course the option of getting a hosted virtual server and serving it from there, which is what I do, but I already had one set up for multiple other reasons, and this can get expensive and confusing fast if you don't have much IT background.

**Comment by XxArmaxX** [comment]
Alright, thank you for the response, I will look into it.

**Comment by lalligood** [comment]
Also, depending on the operating system that you are running your MC
server(s) on, you can self-host. I don't know about Windows or Mac, but
getting nginx or Apache running on a Linux system is moderately easy to get
running. (Expect some initial headaches with getting it configured at first
but it's virtually maintenance-free after that.)

Self-hosting means the same box serving up my map content has the MC world
on the same box. I'd also say that self-hosting makes it easier to serve up
map content when your world(s) becomes *really* big. (I know that my MCv1.8
world by itself is well over 100GB. And I still have my maps from 1.7, 1.9,
& 1.10 on there too.)

--Lance

**Comment by Ferroin** [comment]
Yeah, I can attest to at least nginx working pretty much flawlessly on a Linux box also hosting a Minecraft server (running a MC server is actually part of why I had a hosted virtual server myself).

If you do go that way, I'd personally suggest nginx over Apache, as it's a bit easier to configure and has a much smaller impact on the rest of the system in terms of resources.  I'm not sure how much effort it is to set up on a Mac, but I know from experience that it's pretty easy to set up on Windows too if you have some basic IT background (and it's insanely more secure than IIS).
