### ISSUE TITLE
std::bad_alloc() in ./src/mapcraftercore/mc/region.cpp

### ISSUE THREAD

**Issue by atrixuser** [mapcrafter/mapcrafter#239]
Within  the proc RegionFile::read() 

uint32_t size = *(reinterpret_cast<uint32_t*>(&regiondata[offset]));
Can return 0 when the world has a corrupted block. 

When this occurs 
size = util::bigEndian32(size) - 1;
sets the size to high values 0xffffffff and because its unsigned it will pass the file size  check. It then proceeds to  chunk_data[i].resize(size);   which will cause an attemt to allocate 4294967295 bytes.  

This causes a std::bad_alloc()  crash.

**Comment by atrixuser** [comment]
I am not sure of the side affects of this but as a quick work around I added a  check for size == 0

                // get data size and compression type
                uint32_t size = *(reinterpret_cast<uint32_t*>(&regiondata[offset]));
                if (size == 0) {
                        int x = i % 32;
                        int z = (i - x) / 32;
                        LOG(ERROR) << "Corrupt region '" << filename << "': size of chunk == 0 " << x << ":" << z << ".";
                        return false;
                }
                size = util::bigEndian32(size) - 1;

**Comment by m0r13** [comment]
Great, I'll have a look at implementing this. Do you have an example region file where this applies?

**Comment by atrixuser** [comment]
Sorry to say that after mapcrafter finished i dumped the world in 1.10.2 and recreated it using the same seed 8457533257259635583 it at version 1.11.  I used generator settings in both with wborder set at 5000 square:
generator-settings={"coordinateScale"\:450.0,"heightScale"\:1.0,"lowerLimitScale"\:1450.0,"upperLimitScale"\:1450.0,"depthNoiseScaleX"\:200.0,"depthNoiseScaleZ"\:200.0,"depthNoiseScaleExponent"\:0.5,"mainNoiseScaleX"\:1800.0,"mainNoiseScaleY"\:5000.0,"mainNoiseScaleZ"\:1800.0,"baseSize"\:9.275,"stretchY"\:4.005,"biomeDepthWeight"\:1.105,"biomeDepthOffset"\:0.01,"biomeScaleWeight"\:4.0,"biomeScaleOffset"\:0.01,"seaLevel"\:58,"useCaves"\:true,"useDungeons"\:true,"dungeonChance"\:10,"useStrongholds"\:true,"useVillages"\:true,"useMineShafts"\:true,"useTemples"\:true,"useMonuments"\:true,"useRavines"\:true,"useWaterLakes"\:true,"waterLakeChance"\:100,"useLavaLakes"\:true,"lavaLakeChance"\:100,"useLavaOceans"\:false,"fixedBiome"\:-1,"biomeSize"\:5,"riverSize"\:5,"dirtSize"\:33,"dirtCount"\:12,"dirtMinHeight"\:0,"dirtMaxHeight"\:256,"gravelSize"\:33,"gravelCount"\:12,"gravelMinHeight"\:0,"gravelMaxHeight"\:256,"graniteSize"\:33,"graniteCount"\:12,"graniteMinHeight"\:0,"graniteMaxHeight"\:255,"dioriteSize"\:33,"dioriteCount"\:12,"dioriteMinHeight"\:0,"dioriteMaxHeight"\:255,"andesiteSize"\:33,"andesiteCount"\:12,"andesiteMinHeight"\:0,"andesiteMaxHeight"\:255,"coalSize"\:17,"coalCount"\:25,"coalMinHeight"\:0,"coalMaxHeight"\:255,"ironSize"\:9,"ironCount"\:25,"ironMinHeight"\:0,"ironMaxHeight"\:255,"goldSize"\:9,"goldCount"\:8,"goldMinHeight"\:0,"goldMaxHeight"\:255,"redstoneSize"\:8,"redstoneCount"\:10,"redstoneMinHeight"\:0,"redstoneMaxHeight"\:255,"diamondSize"\:8,"diamondCount"\:8,"diamondMinHeight"\:0,"diamondMaxHeight"\:255,"lapisSize"\:7,"lapisCount"\:2,"lapisCenterHeight"\:125,"lapisSpread"\:100}

The world border fill command will most likely not create an 1.11 world so I dont know if it will produce the same corrupt region. I will try to reproduce it in 1.11.  More to follow....

**Comment by atrixuser** [comment]
The corruption was from a server crash during the world border fill process. The change made does fix the issue.  Thank you.
