### ISSUE TITLE
Signs not detected in 1.11

### ISSUE THREAD

**Issue by Yax** [mapcrafter/mapcrafter#240]
After moving server to 1.11 mapcrafter_markers stopped detecting signs. I tried different configurations and nothing worked. I did some reasearch and somewhere between 1.10.2 and 1.11 the entity id for the signs was changed from `sign` to `minecraft:sign`.

I have changed line 269 in `worldentities.cpp` from:
`if (entity.findTag<nbt::TagString>("id").payload != "Sign")`
to
`if (entity.findTag<nbt::TagString>("id").payload != "minecraft:sign")`
and it worked. Although I'm not sure that this is a correct solution to the problem. I think it might not detect correctly signs in the pre-1.11 worlds.

**Comment by m0r13** [comment]
Thanks for your research! I added it so it should work with new and old signs. I'm going to test it later.

**Comment by mbielski** [comment]
Any idea when this will get merged in? I would imagine that 1.12 will be out soon and it'll probably bring a whole new set of issues.

**Comment by BafDyce** [comment]
@mbielski This is already fixed and merged into master!

If you're building the latest version, `mapcrafter_markers` is able to generate markers. I just tested this with `Mapcrafter version: 2.3.1 (v.2.3.1-5-g4ae3fba)`

**Comment by mbielski** [comment]
I don't have the ability to build it myself and see, so thank you for the update.

**Comment by m0r13** [comment]
I forgot to release an update, I'm sorry. I'll try to do that in the next few days.

**Comment by taziup** [comment]
Hello,
I am using mapcrafter with debian package which is 2.3.1 version. A release should be welcome. Thanks for your great job.
