### ISSUE TITLE
Marker group option "show_default" doesn't work

### ISSUE THREAD

**Issue by OK-Master** [mapcrafter/mapcrafter#242]
If I set the marker group option `show_default` to `false`, the group is still checked on the map and the counter is always 17.

I debugged the website and found that in the file `static/js/handler/marker.js` the line **71** `document.getElementById("cb_group_" + group).checked = false;` throws an exception because the element can't be found.

I replaced the line with the following two lines of code and it's worked as expected:
```
var button = document.querySelector('[data-group="sign"]');
button.classList.remove("list-group-item-info");
```

**Comment by m0r13** [comment]
I fixed the issue you found and investigated. Thanks for pointing that out. I tested the fix locally and it worked, could you test it too? I would close the issue then.

**Comment by OK-Master** [comment]
Your fix work properly, thanks :)
