### ISSUE TITLE
nightlight in world/map end, doesn't work

### ISSUE THREAD

**Issue by el0hh** [mapcrafter/mapcrafter#244]
Here is my configuration:
https://gist.github.com/anonymous/255e4df3178edc2d2a893102c48b6021

I got no configuration error/warning and get always an end in daylight mode.
For orientation we use torches on the ground, in daylight mode it's hard to find them.

![screenshot-end 2016-12-01 10-32-48](https://cloud.githubusercontent.com/assets/24290550/20788561/9d9dbaf4-b7b1-11e6-9005-85329e4a24b9.png)

**Comment by m0r13** [comment]
Your configuration looks fine. I guess the issue is somehow that the sunlight is not properly emulated depending on day/nightlight render mode. Let me try to reproduce this issue.

**Comment by m0r13** [comment]
I got it! I tested it locally and it worked. If you could test it too that would be great, otherwise I'll release a new version with it soon.

**Comment by el0hh** [comment]
I have tested it and it works, great!
