### ISSUE TITLE
APT problem

### ISSUE THREAD

**Issue by Aleszp** [mapcrafter/mapcrafter#247]
Hi!
Since latest apt version there is problem with ubuntu repo:
E: Failed to fetch http://packages.mapcrafter.org/ubuntu/dists/xenial/Release  Invalid 'Valid-Until' entry in Release file /var/lib/apt/lists/packages.mapcrafter.org_ubuntu_dists_xenial_Release

It occurs because of apt's bug - it doesn't recognize JTC time zone.
Simple workaround would be to just change in http://packages.mapcrafter.org/ubuntu/dists/xenial/Release 
line usage of JST to UTC in line 8.

Sincerely Aleszp

**Comment by m0r13** [comment]
Thanks for recognizing that! Should be fixed by now, can you verify that?

**Comment by Aleszp** [comment]
Checked: Problem fixed :).
APT no longer whines about invalid entry :).

//By the way: Big thanks for creating and maintaining Mapcrafter, it's an awesome tool :)//
