### ISSUE TITLE
Player Markers

### ISSUE THREAD

**Issue by Kostronor** [mapcrafter/mapcrafter#248]
Any chance on hoping to get player markers integrated into the main software?

I would love to use them but installing some extra wrappers around the markers tools and populating my world with caches is nothing I really want...

MapCrafter works perfect so it would be good to have this feature added to it.

**Comment by m0r13** [comment]
The player markers need some additional explicit configuration and adds a dependency to a Minecraft Server. Theoretically it would be possible to integrate that, but I wouldn't like the additional dependency and (initially disabled until configured) feature that's not part of Mapcrafters core features.

What do you mean about extra wrappers and world caches? Having a plugin in the Minecraft server running that outputs the player positions to a file is absolutely necessary for this feature.
