### ISSUE TITLE
mapcrafter_markers throwing gzip iostream error

### ISSUE THREAD

**Issue by fleiflei** [mapcrafter/mapcrafter#250]
Hi,

since yesterday when i run mapcrafter_markers i get this error:

> 2017-02-07 16:51:03 [INFO] [progress] Loading entities of world 'myworld' ...
> terminate called after throwing an instance of 'mapcrafter::mc::nbt::NBTError'
>   what():  Error while decompressing gzip data: gzip error: iostream error (4)
> Aborted (core dumped)

I am running arch linux and tried re-compiling the package (from git source) but no success...

Is this a library version issue (i.e. boost)? File permissions seem to be fine...

Best regards,
Flei

**Comment by fleiflei** [comment]
This seems to have been caused by a corrupted entities.nbt.gz located in your_mc_dir/world/region/ and created by mapcrafter itself. I just deleted that file and now it seems to be working again...

This threa lead me on the right track: https://github.com/mapcrafter/mapcrafter/issues/130

**Comment by m0r13** [comment]
I was going to suggest that you delete that file. ;)
