### ISSUE TITLE
Isolated glass panes render as cross.

### ISSUE THREAD

**Issue by ioctl0** [mapcrafter/mapcrafter#260]
Isolated glass pane blocks render as a cross (see attached).  In-game, they appear as thin posts.

<img width="99" alt="screen shot 2017-08-02 at 4 35 46 am" src="https://user-images.githubusercontent.com/7168016/28867625-4ebd3126-773c-11e7-80f4-d6654f3ace35.png">

**Comment by ioctl0** [comment]
![2017-08-02_04 37 13](https://user-images.githubusercontent.com/7168016/28867689-78d81d18-773c-11e7-91f7-e5739476f285.png)

**Comment by elamperti** [comment]
This will be fixed when `world113` is merged! 🎉 (just checked)
![image](https://user-images.githubusercontent.com/910672/121971005-2bbecd80-cd4e-11eb-9a2e-18e8ac240738.png)
(You can see the glass rod near the redstone torch)
