### ISSUE TITLE
Player marker from last known location

### ISSUE THREAD

**Issue by steveabraham** [mapcrafter/mapcrafter#261]
Just curious if there's a way to define a marker in Mapcrafter for the player's last known location when the server last saved?

This is how I currently do it in Overviewer:

`def playerIcons(poi):
    import time
    if poi['id'] == 'Player' and int(time.time()) - int(time.mktime(poi['time'])) <= 900:
        poi['icon'] = "https://minotar.net/body/%s/20.png" % poi['EntityId']
        return "%s" % poi['EntityId']`

It means we can get a rough location without the need for any server plugins (running Vanilla, so can't use the Player Marker mod).

**Comment by gregpechiro** [comment]
I don't know if the author can do this or not. I won't speak for him but he does say on the in the readme he is busy and probably won't be adding new features. I needed to do the same thing for a different reason. I wrote a program to do this. You can find it [here](https://github.com/gregpechiro/playerMarkers). If you need help compiling or setting up let me know. Hope this helps.

**Comment by steveabraham** [comment]
That's awesome, I'll give it a try. Thanks so much.

**Comment by gregpechiro** [comment]
can this be closed?
