### ISSUE TITLE
Empty JPEG image (DNL not supported)

### ISSUE THREAD

**Issue by driftfox** [mapcrafter/mapcrafter#265]
After exploring the map in a straight line out to approximately 650, 3500, I can no longer successfully use mapcrafter. I get the following here message:

```
2017-10-18 01:39:43 [INFO] [default] Scanning worlds...
2017-10-18 01:39:47 [INFO] [default] [1/6] Rendering map world_isometric_day ("Overworld - Day"):
2017-10-18 01:39:47 [INFO] [default] [1.1/1.4] Rendering rotation top-left...
2017-10-18 01:39:47 [INFO] [default] The max zoom level was increased from 8 to 9.
2017-10-18 01:39:47 [INFO] [default] I will move some files around...
Empty JPEG image (DNL not supported)
```

**Comment by lalligood** [comment]
I'm not saying that your map is big (or small), but I can assure you that
many folks here--I for one--have had maps go *much* further than either of
those dimensions you listed--well into the 5 digit range--without issue.
(IIRC, there was one person that has reported some true anomalies after
going out something like 50000 in at least one direction. But I believe
that his error was different than what you've got here.)

   - Would you mind posting your config file?
   - When is the last time that you made any changes to it? If so, what
   was/were the change(s)?
   - And forgive the silly question but, did you verify that you have
   sufficient available disk space? (Again, I've had maps with multiple
   angles/levels/renderings that the mapcrafter directory exceeded 100GB...a
   non-trivial amount of storage!)



--Lance

**Comment by driftfox** [comment]
1. I'd be happy to post my config; I'll add it below to keep all my answers together.
2. The only time I ever changed it was when I copied it from one of my other worlds a week ago and altered the input/output directories.
3. Running `df -h` on this VM reports that it has 12G available on the drive.

Mapcrafter had successfully ran the hour before (I have it on an hourly cron job) and so running out to those coordinates as I mentioned was the only thing I could think that was radically different than anything I had been doing; I had otherwise been staying fairly close to my home base. Perhaps it's completely unrelated to my issue.

Thanks for the quick reply, Lance!

Here's a copy of my config:
```
output_dir = /opt/mscs/maps/rocslaststand/mapcrafter

[global:map]
world = rickoverworld
render_view = isometric
render_mode = daylight
rotations = top-left top-right bottom-right bottom-left
texture_size = 16
image_format = jpeg
jpeg_quality = 65

[world:rickoverworld]
input_dir = /opt/mscs/backups/rocslaststand/world
default_zoom = 3

[world:ricknether]
input_dir = /opt/mscs/backups/rocslaststand/world
dimension = nether
default_zoom = 3
crop_max_y = 55

[world:ricknether2]
input_dir = /opt/mscs/backups/rocslaststand/world
dimension = nether
default_zoom = 3

[map:world_isometric_day]
name = Overworld - Day

[map:world_isometric_night]
name = Overworld - Night
render_mode = nightlight

[map:world_isometric_cave]
name = Overworld - Cave
render_mode = cave

[map:world_topdown_day]
name = Overworld - Topdown
render_view = topdown
texture_size = 6
texture_blur = 2
tile_width = 3

[map:nether_isometric_day]
name = Nether
world = ricknether

[map:nether_isometric_cave]
name = Nether - Cave
world = ricknether2
render_mode = cave
```

**Comment by driftfox** [comment]
Sorry, clicked the wrong button.

**Comment by driftfox** [comment]
I decided to remove my output directory and start Mapcrafter again. I've received no errors this time. Should I leave this bug report open? If I can provide a before and after state of the world in order to reproduce the issue, should I share those? I have access to backups of the world every hour.

**Comment by fjeddy** [comment]
Just had the same issue, to confirm, deleting the output folder solves the problem.

**Comment by m0r13** [comment]
I think I got the issue, the problem was that the tile size was not properly determined and Mapcrafter tried to write empty JPEGs which caused the error.

**Comment by elamperti** [comment]
Considering there are no new comments in this issue, it seems like ec50712 effectively solved it. Closing for now, feel free to leave a comment below if you keep getting this error with recent versions of Mapcrafter.
