### ISSUE TITLE
Side render view not working with tile_width=4

### ISSUE THREAD

**Issue by ligos** [mapcrafter/mapcrafter#284]
Found an issue with `render_view = side` and `tile_width=4`. The result looks like a JRPG with the sprites all mis-matched!

Other render views appear unaffected, and I haven't tried other `tile_width`s. Although I know the default tile width is OK.

![side render tile_width 4 bug](https://user-images.githubusercontent.com/3079652/46285557-34cbd880-c5bf-11e8-89e1-4f29b490c1c1.PNG)

Relevant config:

```
[map:Survival_Easy_side]
name = Survival Easy - side
world = Survival_Easy_Overworld
texture_size = 12
tile_width = 4
png_indexed = true
render_mode = plain
render_view = side

```

[Full config](https://minecraft.ligos.net/worlds/Survival_Easy/config-survival-easy.conf.txt)

**Comment by m0r13** [comment]
Stupid little mistake, this should fix it. :)

**Comment by ligos** [comment]
Perfect!
