### ISSUE TITLE
Compilation errors on MacOS with homebrew

### ISSUE THREAD

**Issue by kbroestl** [mapcrafter/mapcrafter#285]
Picking up the thread from the general world113 branch/issues

Latest updates seem to have fixed the previous compilation issue, but now I get a new one:
`
mapcrafter/src/mapcraftercore/renderer/blockimages.cpp:320:3: error: 
      non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list
      [-Wc++11-narrowing]
                1.0 - x,
                ^~~~~~~
mapcrafter/src/mapcraftercore/renderer/blockimages.cpp:320:3: note: 
      insert an explicit cast to silence this issue
                1.0 - x,
                ^~~~~~~
                static_cast<float>( )
`

**Comment by m0r13** [comment]
For other users reading this, the original problem was:

> mapcrafter/src/mapcraftercore/mc/java.h:61:26: error: constexpr variable 'F2' must be initialized by a constant expression static constexpr double F2 = 0.5 * (sqrt(3) - 1.0); ^ ~~~~~~~~~~~~~~~~~~~~~ mapcrafter/src/mapcraftercore/mc/java.h:61:38: note: non-constexpr function 'sqrt<int>' cannot be used in a constant expression static constexpr double F2 = 0.5 * (sqrt(3) - 1.0); ^ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:970:1: note: declared here sqrt(_A1 __lcpp_x) _NOEXCEPT {return ::sqrt((double)__lcpp_x);} ^ In file included from mapcrafter/src/mapcraftercore/mc/java.cpp:20: mapcrafter/src/mapcraftercore/mc/java.h:62:26: error: constexpr variable 'G2' must be initialized by a constant expression static constexpr double G2 = (3.0 - sqrt(3)) / 6.0; ^ ~~~~~~~~~~~~~~~~~~~~~ mapcrafter/src/mapcraftercore/mc/java.h:62:38: note: non-constexpr function 'sqrt<int>' cannot be used in a constant expression static constexpr double G2 = (3.0 - sqrt(3)) / 6.0; ^ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:970:1: note: declared here sqrt(_A1 __lcpp_x) _NOEXCEPT {return ::sqrt((double)__lcpp_x);} ^
> 
> MacOS 10.12.6, using homebrew for libraries. Fresh clone of mapcrafter world113 branch fails as above.
> Build of master branch succeeds with several warnings.
@kbroestl

**Comment by kbroestl** [comment]
Success! It's a bit noisy (quite a few warnings) but compiles successfully.

**Comment by m0r13** [comment]
Good to hear. I'll close it later so the others can still find it here.

**Comment by kbroestl** [comment]
Sounds good. Thanks for the quick turnaround, and good luck with your studies!

**Comment by fjeddy** [comment]
Can confirm that this issue is fixed :)
