### ISSUE TITLE
Mapcrafter not finding libraries in gentoo.

### ISSUE THREAD

**Issue by shelterx** [mapcrafter/mapcrafter#286]
I get this error when compiling Mapcrafter for MC 1.13. I didn't find any info on it.
Maybe boost is too new on my system, 1.65.0?
`[ 72%] Linking CXX executable mapcrafter_export mapcraftercore/libmapcraftercore.so: undefined reference to png_create_info_struct mapcraftercore/libmapcraftercore.so: undefined reference to png_read_info mapcraftercore/libmapcraftercore.so: undefined reference to png_sig_cmp mapcraftercore/libmapcraftercore.so: undefined reference to png_set_strip_16 mapcraftercore/libmapcraftercore.so: undefined reference to png_malloc mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::deflated mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&) mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_std_error mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_CreateDecompress mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*) mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_start_compress mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::dir_itr_close(void*&, void*&) mapcraftercore/libmapcraftercore.so: undefined reference to png_get_io_ptr mapcraftercore/libmapcraftercore.so: undefined reference to png_set_expand_gray_1_2_4_to_8 mapcraftercore/libmapcraftercore.so: undefined reference to pthread_create mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::zlib_base::before(char const*&, char const*, char*&, char*) mapcraftercore/libmapcraftercore.so: undefined reference to png_set_add_alpha mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_set_quality mapcraftercore/libmapcraftercore.so: undefined reference to png_set_read_fn mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_read_header mapcraftercore/libmapcraftercore.so: undefined reference to png_destroy_read_struct mapcraftercore/libmapcraftercore.so: undefined reference to png_get_color_type mapcraftercore/libmapcraftercore.so: undefined reference to png_set_IHDR mapcraftercore/libmapcraftercore.so: undefined reference to png_set_rows mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib_error::check(int) mapcraftercore/libmapcraftercore.so: undefined reference to png_destroy_write_struct mapcraftercore/libmapcraftercore.so: undefined reference to png_set_swap_alpha mapcraftercore/libmapcraftercore.so: undefined reference to png_get_bit_depth mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_destroy_decompress mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::okay mapcraftercore/libmapcraftercore.so: undefined reference to png_create_read_struct mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::zlib_base::xdeflate(int) mapcraftercore/libmapcraftercore.so: undefined reference to png_set_sig_bytes mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::zlib_base::reset(bool, bool) mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_stdio_dest mapcraftercore/libmapcrafterco re.so: undefined reference to png_set_bgr mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::gzip_footer::reset() mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::stream_end mapcraftercore/libmapcraftercore.so: undefined reference to png_set_longjmp_fn mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_finish_compress mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::no_flush mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::path::filename() const mapcraftercore/libmapcraftercore.so: undefined reference to png_get_image_height mapcraftercore/libmapcraftercore.so: undefined reference to png_write_png mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::best_speed mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::zlib_base::xinflate(int) mapcraftercore/libmapcraftercore.so: undefined reference to png_set_gray_to_rgb mapcraftercore/libmapcraftercore.so: undefined reference to png_set_tRNS mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*) mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*) mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_destroy_compress mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::current_path(boost::system::error_code*) mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) mapcraftercore/libmapcraftercore.so: undefined reference to png_set_write_fn mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::zlib_base::zlib_base() mapcraftercore/libmapcraftercore.so: undefined reference to boost::system::system_category() mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_finish_decompress mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_set_defaults mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::gzip_footer::process(char) mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_start_decompress mapcraftercore/libmapcraftercore.so: undefined reference to png_get_image_width mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*) mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::best_compression mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::last_write_time(boost::filesystem::path const&, boost::system::error_code*) mapcraftercore/libmapcraftercore.so: undefined reference to png_read_end mapcraftercore/libmapcraftercore.so: undefined reference to png_read_image mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_write_scanlines mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::zlib_base::~zlib_base() mapcraftercore/libmapcraftercore.so: undefined reference to png_create_write_struct mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*) mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::gzip_header::process(char) mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::gzip_header::reset() mapcraftercore/libmapcraftercore.so: undefined reference to png_read_update_info mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::default_strategy mapcraftercore/libmapcraftercore.so: undefined reference to png_set_palette_to_rgb mapcraftercore/libmapcraftercore.so: undefined reference to boost::system::generic_category() mapcraftercore/libmapcraftercore.so: undefined reference to png_free mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_CreateCompress mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::sync_flush mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*) mapcraftercore/libmapcraftercore.so: undefined reference to png_set_interlace_handling mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_read_scanlines mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::path::operator/=(boost::filesystem::path const&) mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool) mapcraftercore/libmapcraftercore.so: undefined reference to boost::filesystem::path::parent_path() const mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::finish mapcraftercore/libmapcraftercore.so: undefined reference to png_set_PLTE mapcraftercore/libmapcraftercore.so: undefined reference to jpeg_stdio_src mapcraftercore/libmapcraftercore.so: undefined reference to boost::iostreams::zlib::default_compression collect2: error: ld returned 1 exit status make[2]: *** [CMakeFiles/mapcrafter_export.dir/build.make:96: mapcrafter_export] Error 1 make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mapcrafter_export.dir/all] Error 2 make: *** [Makefile:130: all] Error 2`

**Comment by m0r13** [comment]
There are also errors linking to libpng and libjpeg. What kind of linux with which versions of libpng/libjpeg are you running?

**Comment by shelterx** [comment]
Gentoo Base System release 2.4.1
libpng 1.45
libjpeg-turbo 1.2.1 (seems to be pulled in by virtual/jpeg-62)
I understand if jpeg-turbo might be a problem tho', not sure how compatible it is with normal libjpeg.

**Comment by m0r13** [comment]
jpeg-turbo shouldn't be a problem. I'm using it myself and for building the debian packages too. CMake must do something wrong with running the linker linking the libraries to Mapcrafter. But there are also no errors that boost/libpng/jpeg are not found. I'm not really sure right now what could cause this.

**Comment by shelterx** [comment]
Hmm, how should CMakeFiles/mapcrafter.dir/link.txt look like?
Mine looks like this:
/usr/bin/c++    -rdynamic CMakeFiles/mapcrafter.dir/mapcrafter.o -o mapcrafter -Wl,-rpath,/home/user/tmp/mapcrafter-world113/src/mapcraftercore: mapcraftercore/libmapcraftercore.so

There's no mention of boost libraries there?

**Comment by shelterx** [comment]
Fixed it by adding "-lboost_program_options -lboost_iostreams -lboost_system -lboost_filesystem -lpng -lz -ljpeg -lpthread" to link.txt, no idea why it doesn't find the libraries tho'.
I've never had trouble compiling anything else on this system.
Some output from ldd mapcrafter after successful compile:
        libboost_program_options.so.1.65.0 => /usr/lib64/libboost_program_options.so.1.65.0 (0x00007f6e565e2000)
        libboost_iostreams.so.1.65.0 => /usr/lib64/libboost_iostreams.so.1.65.0 (0x00007f6e563c4000)
        libboost_system.so.1.65.0 => /usr/lib64/libboost_system.so.1.65.0 (0x00007f6e561bf000)
        libboost_filesystem.so.1.65.0 => /usr/lib64/libboost_filesystem.so.1.65.0 (0x00007f6e55fa4000)

**Comment by shelterx** [comment]
Now it compiles fine, I don't know what was wrong. I rebooted the server because of a new kernel, that's the only "change" I did. Must've been something odd with the environment variables.
You can close this.
