### ISSUE TITLE
`world:crop_unpopulated_chunks = true` crops the whole map!

### ISSUE THREAD

**Issue by ligos** [mapcrafter/mapcrafter#289]
I get nothing rendered at all when I set `crop_unpopulated_chunks = true`!

Looking in the code, this seems to be compared to `Chunk.terrain_populated` in `mapcrafter.mc.Chunk::checkBlockWorldCrop()`. But `terrain_populated` is only set in `Chunk::Chunk()` to false.

https://minecraft.ligos.net/worlds/Mapcrafter_Test/index.html#MapcrafterTest_Overworld_isometric_cropunpopulatedchunks/0/0/117/229/64

https://minecraft.ligos.net/worlds/Mapcrafter_Test/config-mapcrafter-test.conf.txt

**Comment by m0r13** [comment]
Oh, that will be one of the option to be removed too. Unpopulated chunks will be cropped in 1.13 automatically as they are also missing biome and light data.
