### ISSUE TITLE
Blocks.png in root? folder

### ISSUE THREAD

**Issue by fjeddy** [mapcrafter/mapcrafter#290]
Version: 1.13.1 (Latest world113)

I'm using Mapcrafter on both Ubuntu and MacOS, the problem occurs in both servers. Whenever mapcrafter runs, it puts an empty `blocks.png` in the root folder of my project, quite annoying, as everything is on git and i constantly end up deleting it manually to avoid having it in my repo.

```
output_dir = ../data/map

[global:map]
world = world
render_mode = daylight
texture_size = 16
image_format = jpeg
jpeg_quality = 85

[world:world]
default_zoom = 3
input_dir = ../data/server/world

[map:isometric]
name = Isometric
rotations = top-left top-right bottom-right bottom-left
render_view = isometric

[map:topdown]
name = Topdown
rotations = top-left
render_view = topdown
texture_blur = 2
tile_width = 3
jpeg_quality = 100
```

Will leave a `blocks.png` in the root folder from output, aka `../`

**Comment by m0r13** [comment]
Thanks for reminding me about this, I completely forgot about it. Just removed it.

Don't worry about the label. I realized myself that you guys can't assign it.
