### ISSUE TITLE
Support Unix & Windows line endings in block_dir text files

### ISSUE THREAD

**Issue by ligos** [mapcrafter/mapcrafter#298]
Both Blockcrafter and Mapcrafter appear to work with native line endings, that is `\n` in Linux and `\r\n` in Windows (not sure if OSX uses `\n` or `\r` these days). So, if you run Blockcrafter to generate new `block_dir` files, and then Mapcrafter on the same OS, all is well. If you run Blockcrafter in Windows and then Mapcrafter on Linux, you get an error:

```
Invalid first line in block info file <blah>!
Line 1: 6 8 32

```

(Note the sneaky `\r` at the end of the line - no, of course you didn't, it's whitespace after all!!)

Error is from blockimages.cpp RenderedBlockImages::loadBlockImages() on line 547.

Can be worked around by converting the line endings in most text editors. So not a really high priority.

[Possible Stackoverflow answer](https://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf).

**Comment by m0r13** [comment]
I've been removing excess whitespace characters from the lines when parsing the block files, but forgot to do it with the first one!

**Comment by m0r13** [comment]
Can you try if this fixes it?

**Comment by ligos** [comment]
Confirmed fixed! You one hybrid Linux + Windows user is happy!
