### ISSUE TITLE
Ubuntu 18.04 Boost cmake issue world113

### ISSUE THREAD

**Issue by mhardin18** [mapcrafter/mapcrafter#305]
I don't think that this is an actual issue with mapcrafter, but rather something about my build environment. I'm hoping that someone here might have some ideas that I haven't tried and eventually I'll find a resolution that may help others in the future.

I am trying to build the world113 branch on Ubuntu 18.04 with Boost 1.65.1 libraries installed from apt. When executing cmake, it is unable to locate the boost iostreams libraries and thus fails. 

I'm about 20 years removed from C++ development, and unfamiliar with cmake and boost, but I'm knowledgeable on Ubuntu and it was rather easy for me to figure out the CMakeLists.txt file and the various functions. I've googled my brains out trying a lot of different things I found may be relevant but cannot find a solution to why cmake is failing to find the iostreams library.

My build environment is a relatively fresh install of Ubuntu 18.04 to host my Minecraft servers. Those are working without issue. So seeing there was a near complete update to Mapcrafter for 1.13, I wanted to give it a try; consequently running into the cmake issues. I pulled the base branch as well and tried that and got the same issues. So again, I don't think this is directly a mapcrafter issue, though it is possible there might be a directive in cmake that might resolve the problem.

Please let me know what other info I can provide that might help those of you reading this to help me solve the issue.

I've attached a bunch of supporting files; the specific error from cmake is
`
CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.65.1

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_iostreams

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:54 (find_package)
`

[buildEnvironment.txt](https://github.com/mapcrafter/mapcrafter/files/2588058/buildEnvironment.txt)
[CMakeCache.txt](https://github.com/mapcrafter/mapcrafter/files/2588059/CMakeCache.txt)
[CMakeError.log](https://github.com/mapcrafter/mapcrafter/files/2588061/CMakeError.log)
[CMakeOutput.log](https://github.com/mapcrafter/mapcrafter/files/2588062/CMakeOutput.log)

**Comment by ligos** [comment]
I'm running Debian 9 Stretch in WSL. Way easier to build Mapcrafter in Linux than Windows.
Here's the *boost* related packages I have. Looks like I installed all the `-dev` packages.

```
msn@AdmiralAckbar:~$ apt list --installed | grep boost
libboost-dev/stable,now 1.62.0.1 amd64 [installed]
libboost-filesystem-dev/stable,now 1.62.0.1 amd64 [installed]
libboost-filesystem1.62-dev/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-filesystem1.62.0/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-iostreams-dev/stable,now 1.62.0.1 amd64 [installed]
libboost-iostreams1.62-dev/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-iostreams1.62.0/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-program-options-dev/stable,now 1.62.0.1 amd64 [installed]
libboost-program-options1.62-dev/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-program-options1.62.0/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-regex1.62-dev/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-regex1.62.0/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-system-dev/stable,now 1.62.0.1 amd64 [installed]
libboost-system1.62-dev/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost-system1.62.0/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
libboost1.62-dev/stable,now 1.62.0+dfsg-4 amd64 [installed,automatic]
```

And looks like the actual library ended up in `/usr/lib/x86_64-linux-gnu`.

```
msn@AdmiralAckbar:~$ dpkg -L libboost-iostreams1.62-dev
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libboost_iostreams.a
/usr/share
/usr/share/doc
/usr/share/doc/libboost-iostreams1.62-dev
/usr/share/doc/libboost-iostreams1.62-dev/changelog.Debian.gz
/usr/share/doc/libboost-iostreams1.62-dev/copyright
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so
```

Might help. Maybe.

**Comment by mhardin18** [comment]
```
> 
> Might help. Maybe.

Thanks @ligos, that did help I think... made me realize that the iostreams dev package is missing. So I went and tried the following...

`xyz@minecraft:~/mapcrafter$ sudo apt-get install Boost.Iostreams
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libboost-iostreams1.65-dev' for regex 'Boost.Iostreams'
Note, selecting 'libboost-iostreams1.65.1' for regex 'Boost.Iostreams'
libboost-iostreams1.65.1 is already the newest version (1.65.1+dfsg-0ubuntu5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
xyz@minecraft:~/mapcrafter$ sudo apt-get install libboost-iostreams1.65-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libboost-iostreams1.65-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libboost-iostreams1.65-dev' has no installation candidate
`


So it seems that libboost-iostreams1.65-dev is missing  from the Ubuntu repositories.  Once I hunt down or build a binary for it I'll follow up.

**Comment by mhardin18** [comment]
So that indeed was the issue, missing the iostreams-dev package.  After building boost 1.68 from source, mapcrafter also builds just fine.

'
Package libboost-iostreams1.65-dev is not available, but is referred to by another package.
'
