### ISSUE TITLE
Debian repository

### ISSUE THREAD

**Issue by ErMaqui** [mapcrafter/mapcrafter#309]
I know maybe this is not the place to report this.

Are Debian repositories maintained? From some time, there's an error with the signature.

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.mapcrafter.org/debian stretch Release: The following signatures were invalid: EXPKEYSIG B6F77E28FE4F4EAC Moritz Hilscher (m0r13) <buildbot@mapcrafter.org>
W: Failed to fetch http://packages.mapcrafter.org/debian/dists/stretch/Release.gpg  The following signatures were invalid: EXPKEYSIG B6F77E28FE4F4EAC Moritz Hilscher (m0r13) <buildbot@mapcrafter.org>

I've tried to re-download the key, but the error is still present.

Thanks,

**Comment by kepicorp** [comment]
I had to rebuild from the source that work swiftly on any debian release I tried so far.

**Comment by ErMaqui** [comment]
I think now the problem is solved. I've do an apt-get update and I didn't get the signature error.
