### ISSUE TITLE
Invalid texture directory

### ISSUE THREAD

**Issue by BigIronFIN** [mapcrafter/mapcrafter#313]
Hi,
trying to make a map for v. 1.13. I was able to install the 113 branch, and I extracted textures from the .jar file. Now I get a bunch of warnings about it being unable to load textures and an error when trying to run mapcrafter:
`2018-12-16 23:23:03 [ERROR] [default] Invalid texture directory '/home/pekka/.mapcrafter/textures/'. See previous log messages.`
My output from "./mapcrafter_textures.py -f ~/.minecraft/versions/1.13.2/1.13.2.jar ~/.mapcrafter/textures/" is here:
`Extracting block images:
 - Found 0 block images.
 - Extracted 0.
 - Skipped 0 (Use -f to force overwrite).

Extracting other textures:
 - Extracting /home/pekka/.mapcrafter/textures/entity/chest/normal.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/chest/normal_double.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/chest/ender.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/chest/trapped.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/chest/trapped_double.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/colormap/foliage.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/colormap/grass.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_black.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_blue.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_brown.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_cyan.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_gray.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_green.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_light_blue.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_lime.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_magenta.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_orange.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_pink.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_purple.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_red.png ... extracted.
 - Extracting entity/shulker/shulker_silver.png ... not found!
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_white.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/shulker/shulker_yellow.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/black.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/blue.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/brown.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/cyan.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/gray.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/green.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/light_blue.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/lime.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/magenta.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/orange.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/pink.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/purple.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/red.png ... extracted.
 - Extracting entity/bed/silver.png ... not found!
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/white.png ... extracted.
 - Extracting /home/pekka/.mapcrafter/textures/entity/bed/yellow.png ... extracted.`

I read through https://github.com/mapcrafter/mapcrafter/issues/221, but I really don't understand what I'm doing here :)

Please help?

**Comment by m0r13** [comment]
Are you sure you have built the 113 branch? Mapcrafter on that branch shouldn't need the texture files anymore, only the generated block files. Otherwise, what log messages are there _before_ the `Invalid texture directory '/home/pekka/.mapcrafter/textures/'. See previous log messages.` ?

**Comment by BigIronFIN** [comment]
I'm feeling pretty stupid right now :)
Thanks for the quick reply. I had indeed built the master branch. I built the 113 and now it's working.
Thanks a bunch!
