### ISSUE TITLE
Still get  Unknown tag type with id 12 errors

### ISSUE THREAD

**Issue by Bodnov** [mapcrafter/mapcrafter#314]
Hi,
I installed next version of mapcrafter on Ubuntu 16.04.1 LTS using apt-get:
Minecraft world 1.13.2
Mapcrafter version: 2.4 (v.2.3.1-52-g5aa16da)
I started up the Minecraft server with option --forceUpgrade and more the 560.000 chucks are updated.
But stil I got only next errors when running mapcrafter and nothing is rendered:
2018-12-30 17:41:27 [ERROR] [default] Unable to read chunk at -218:-790 : Unknown tag type with id 12. NBT data stream may be corrupted.

I noticed that mapcrafter --mc-version says 1.12

What am I doing wrong?

**Comment by Bodnov** [comment]
Downloaded the nightly debian package. Managed to get that version installed and it is now working ok.

**Comment by Hampfh** [comment]
Hi, I have the same problem. How exactly did you change to the nightly package? I downloaded mapcrafters via cloning the repository but can't wrap my head around how to swap. I downloaded the latest version and yet --mc-version shows 1.12. 

I'm running Ubuntu 18.04
