### ISSUE TITLE
Mapviewer not working 

### ISSUE THREAD

**Issue by MidhunVijayan** [mapcrafter/mapcrafter#315]
Hi,

2018-12-31 10:40:41 [ERROR] [default] Rendering of world 'world0'  is not supported.
2018-12-31 10:40:41 [ERROR] [default] Mapcrafter supports only worlds of Minecraft 1.13 and newer
2018-12-31 10:40:41 [ERROR] [default] See Mapcrafter legacy for rendering of older worlds. TODO

getting error while generating the maps. Please help me on this?

**Comment by ligos** [comment]
You're using the latest version of Mapcrafter on a pre-1.13 world. You'll either need to a) upgrade your world and using Minecraft 1.13 or b) use one of the [legacy Mapcrafter versions](https://mapcrafter.org/downloads/main).

**Comment by MidhunVijayan** [comment]
Hi,

Thank you for your great help. 
We are on debian 9 (Stretch) . but we couldn't find any legacy version for mapcrafter for this. In the mentioned link it's also forbidden.

Can you suggest me on this?

**Comment by ligos** [comment]
I've tagged the author about the forbidden error. 
If you're on Minecraft 1.12, Mapcrafter 2.4 and Debian 9, you could try adding the dpkg repository or building from source. Both have instructions on the [Installation Documentation](https://docs.mapcrafter.org/builds/stable/installation.html) page.

(Note: I got the 1.13 branch of Mapcrafter building on Stretch OK, but I remember some problems building the master branch for Minecraft 1.12 - sorry, it was a while ago, the details escape me).

Murray

**Comment by MidhunVijayan** [comment]
Hi ,

Thank you for your response.
This is to inform you that I have already tried with the installation of mapcrafter from the source, with world113 branch. 
https://github.com/mapcrafter/mapcrafter/commits/world113.  

The game is on 1.12.2, why it doesn’t work under 1.13 ?

Thank you!

**Comment by ligos** [comment]
Try building from the `master` branch. `world113` is the branch for Minecraft 1.13, `master` is for pre-1.13.

There were substantial changes to how Minecraft stores world data in 1.13, and equally substantial changes to how Mapcrafter renders 1.13 worlds. Unfortunately, Mapcrafter isn't backwards compatible.

**Comment by MidhunVijayan** [comment]
Hi,

Thank you for your great help :)

**Comment by elamperti** [comment]
Hopefully by now this problem has been solved for OP! 

In any case it will be good to double-check that the readme _and_ the documentation mention which Mapcrafter version to use for pre/post Minecraft 1.13 maps.

I'll be closing this issue for now (let's keep an eye on #312 to see when package downloads are fixed) :slightly_smiling_face:
