### ISSUE TITLE
Only rendering first chunk 1.13.2

### ISSUE THREAD

**Issue by cjhelmkamp** [mapcrafter/mapcrafter#317]
I rebuilt my minecraft server on ubuntu 18.04 and built mapcrafter from source using the 113world branch. Rendering the map works but only for the first chunk. There are no errors when rendering. 

I have tried to Force the render, delete the output directory, checked permissions (I run mapcrafter as its own user part of the minecraft group), delete the program and remake/reinstall.

Thanks for the program, it is quite awesome. 

Chris

**Comment by batekulve** [comment]
Is this a new map in 1.13 or was it created in an older version?

If it's older, then you have to upgrade all chunks to a 1.13 format by passing `--forceUpgrade` to the server jar. You should only have to do this once and it's permanent. Old format chunks will not be rendered.

**Comment by cjhelmkamp** [comment]
It was a new map for 1.13.2

**Comment by batekulve** [comment]
Can you paste your config file here?

**Comment by cjhelmkamp** [comment]
It is attached, i have commented a lot out when testing. 

[render.txt](https://github.com/mapcrafter/mapcrafter/files/2814814/render.txt)

**Comment by batekulve** [comment]
Sorry, there's nothing else that I can tell that would cause this.

**Comment by cjhelmkamp** [comment]
I tried a --ForceUpgrade just in case and it did not help. In Issue 275 at the very end it looks like they may have altered the map coordinates again.

https://github.com/mapcrafter/mapcrafter/issues/275#issuecomment-453457213

**Comment by batekulve** [comment]
Yes, if you're using a snapshot that could very well be the problem.

**Comment by 25A0** [comment]
@cjhelmkamp With the following (very naive) patch to `chunk.cpp` I was able to render a 1.14 snapshot world. The patch:
 - accepts sections that contain "full" as status string, in addition to the other status strings. I found this status string in a number of chunks in my world.
 - accepts sections even if the `BlockLight` or `SkyLight` tags are missing, and instead check whether they are present before attempting to copy them. It seems that these tags are not present in all sections in the new chunk format. I don't know enough about the chunk format to explain when they are omitted, but my world rendered just fine with this hack.

I've only tested this with one world, containing chunks that were generated with 1.13, 18w45a, and 19w06a. It fails to render parts of the bamboo plants, but other than that I've not seen any issues yet.
I hope this helps, maybe as a temporary solution until the new chunk format is officially supported.

```
diff --git a/src/mapcraftercore/mc/chunk.cpp b/src/mapcraftercore/mc/chunk.cpp
index 12f318b..6c78f41 100644
--- a/src/mapcraftercore/mc/chunk.cpp
+++ b/src/mapcraftercore/mc/chunk.cpp
@@ -173,7 +173,7 @@ bool Chunk::readNBT(mc::BlockStateRegistry& block_registry, const char* data, si
                const nbt::TagString& tag = level.findTag<nbt::TagString>("Status");
                // completely generated chunks in fresh 1.13 worlds usually have status 'fullchunk' or 'postprocessed'
                // however, chunks of converted <1.13 worlds don't use these, but the state 'mobs_spawned'
-               if (!(tag.payload == "fullchunk" || tag.payload == "postprocessed" || tag.payload == "mobs_spawned")) {
+               if (!(tag.payload == "fullchunk" || tag.payload == "full" || tag.payload == "postprocessed" || tag.payload == "mobs_spawned")) {
                        return true;
                }
        }
@@ -210,8 +210,6 @@ bool Chunk::readNBT(mc::BlockStateRegistry& block_registry, const char* data, si
                if (!section_tag.hasTag<nbt::TagByte>("Y")
                //              || !section_tag.hasArray<nbt::TagByteArray>("Blocks", 4096)
                //              || !section_tag.hasArray<nbt::TagByteArray>("Data", 2048)
-                               || !section_tag.hasArray<nbt::TagByteArray>("BlockLight", 2048)
-                               || !section_tag.hasArray<nbt::TagByteArray>("SkyLight", 2048)
                                || !section_tag.hasArray<nbt::TagLongArray>("BlockStates")
                                || !section_tag.hasTag<nbt::TagList>("Palette"))
                        continue;
@@ -248,9 +246,6 @@ bool Chunk::readNBT(mc::BlockStateRegistry& block_registry, const char* data, si
                        palette_lookup[i] = block_registry.getBlockID(block);
                }

-               const nbt::TagByteArray& block_light = section_tag.findTag<nbt::TagByteArray>("BlockLight");
-               const nbt::TagByteArray& sky_light = section_tag.findTag<nbt::TagByteArray>("SkyLight");
-
                // create a ChunkSection-object
                ChunkSection section;
                section.y = y.payload;
@@ -273,8 +268,16 @@ bool Chunk::readNBT(mc::BlockStateRegistry& block_registry, const char* data, si
                        continue;
                }

-               std::copy(block_light.payload.begin(), block_light.payload.end(), section.block_light);
-               std::copy(sky_light.payload.begin(), sky_light.payload.end(), section.sky_light);
+               if(section_tag.hasArray<nbt::TagByteArray>("BlockLight", 2048))
+               {
+                 const nbt::TagByteArray& block_light = section_tag.findTag<nbt::TagByteArray>("BlockLight");
+                 std::copy(block_light.payload.begin(), block_light.payload.end(), section.block_light);
+               }
+               if(section_tag.hasArray<nbt::TagByteArray>("SkyLight", 2048))
+               {
+                 const nbt::TagByteArray& sky_light = section_tag.findTag<nbt::TagByteArray>("SkyLight");
+                 std::copy(sky_light.payload.begin(), sky_light.payload.end(), section.sky_light);
+               }

                // add this section to the section list
                section_offsets[section.y] = sections.size();
```
(edit: use `git apply --ignore-space-change file-containing-this-patch.diff` to apply the patch. GitHub changed the tabs to spaces, making `ignore-space-change` necessary...)

**Comment by cjhelmkamp** [comment]
I have the world114 update working from miclav. I am going to close this.

Thanks for your help!
