### ISSUE TITLE
Building Mapcrafter on Windows

### ISSUE THREAD

**Issue by batekulve** [mapcrafter/mapcrafter#321]
Hi,

Does anyone know if the instructions on [this page](https://github.com/mapcrafter/mapcrafter-buildfiles/tree/master/windows) still work? I'd like to make some tweaks, and though I have a Linux system nothing is set up on it.

If you're curious, I'm going to try to make it so that the cavelight render mode only renders lit blocks. This should make stuff we build underground a lot easier to see than in the usual cave renders.

Thanks.

**Comment by batekulve** [comment]
Well, I've given it my best shot and I don't think I'll be able to get it to work.
I think the main problem here is that these instructions and batch files are all 5 years old. I've tried my best to find and use 5-year-old versions of these libraries and tools but I've only gotten to the 'build libpng' step. There are some errors about failing to create symlinks, then it fails due to a missing file. I've tried with both old and new versions of CMake, NASM, and libraries. I'm not sure how I can install an older version of MinGW.
If no one else has any advice, I guess I'll go install ArchLinux.

**Comment by ligos** [comment]
I spent about 10 minutes trying to build it with VS2017, and gave up.
Easiest way to build Mapcrafter in Windows is to cheat - the Windows Subsystem for Linux (Win 10 only) works a treat to build and run!
(Although don't let that dissuade you from installing ArchLinux)

**Comment by batekulve** [comment]
Can this build a Windows executable? Because mapcrafter is ultimately not running on my machine, but on my dad's Windows machine where the Minecraft server is hosted.

EDIT: I guess if the subsystem can access the Windows filesystem then it can just be run through the subsystem.

**Comment by ligos** [comment]
As long as your Minecraft host has WSL, you're fine. It can access your local Windows partitions without problem.

Otherwise you'd need to map / mount network drives and run from another PC. Should work, but its definitely not how I'm doing it!

**Comment by batekulve** [comment]
Thanks for the help, I never even knew WSL existed. I got it all to build and run... once. 

After making some modifications I was not able to build it again, though the errors seemed unrelated to my changes. The file I changed built fine, then there were many errors about undefined references to `boost::program_options`. This package is definitely installed and up-to-date, so I don't know what's going on here.

EDIT: At first glance it seems like a similar issue to issue #305 but my problem is during make, not cmake. And it was able to install boost-iostreams1.65 just fine.

**Comment by ligos** [comment]
Very strange. Once I had all the packages installed and switched branch to world113, I didn't have any problems building.

Actually, that's a small lie. I did have problems with line endings - some parts of Mapcrafter expect unix `\n` newlines and don't cope with windows `\r\n` new lines. I think they related to the VERSION file though.

**Comment by batekulve** [comment]
Okay, it worked once I deleted all the mapcrafter code, restored a fresh download of the source, pasted in my changed .cpp file, then rebuilt. And my changes did what I expected them to do too!
[Here is the result.](http://btekulve.net/MBSurvivalMap/#Caves/0/3/99/294/64)
