### ISSUE TITLE
General Linux compatibility

### ISSUE THREAD

**Issue by katzmoor** [mapcrafter/mapcrafter#324]
There are plenty of Debian packages, but no general TARs as far as the eye can see. This is preventing me from using the program on the particular variant of Linux I use.

**Comment by fryfrog** [comment]
Just get the source?

**Comment by bemk** [comment]
@katzmoor There's a download or clone button on the main page of the project. If you select the zip option, you'll be able to get the source that way.

**Comment by elamperti** [comment]
@katzmoor You can get the source [as a zip](https://github.com/mapcrafter/mapcrafter/archive/master.zip) (or clone it with `git`), then build it from there so it works in your machine. Check [the docs](https://mapcrafter.readthedocs.io/en/latest/installation.html#building-from-source) for more information on that! 

Closing this issue for now, feel free to comment below or open a new one if needed.
