### ISSUE TITLE
1.14 Support?

### ISSUE THREAD

**Issue by Sushiman42** [mapcrafter/mapcrafter#328]
After some testing I believe the newest update will break Mapcrafter. Is there any plan for support for 1.14? Or is there an easy fix to render newer worlds?

**Comment by igtampe** [comment]
There was [this crude patch](https://gist.github.com/25A0/0363e8b7128b365cde65cec609ac6e55) made, but I haven't seen any pre-compiled versions. You'd need to apply this to the source.

**Comment by miclav** [comment]
Additionally, if you wish, I’ve sent a merge request containing this patch as well as sprite map update for the new blocks. https://github.com/mapcrafter/mapcrafter/pull/327

**Comment by m0r13** [comment]
The PR can be merged soon and I will make pre-compiled versions available again. :)

**Comment by Sushiman42** [comment]
Thanks for the quick fix, I'll try and implement it now. I look forward to the pre-compiled versions.

**Comment by shelterx** [comment]
Hmm, what branch is this patch against? I tried master and world113 branches, I get rejects on both.
EDIT:
For those who are wondering the same thing, the patch is currently in the world113 branch.

**Comment by neotherack** [comment]
@shelterx 
Did you build from world113 branch code?
I clonned git from that branch but I cannot "make" the project.

1) cmake .     (from src folder)
2) make         (error)

Did you deal with it?

ERROR:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
