### ISSUE TITLE
Blank map generated for Minecraft 1.14 world

### ISSUE THREAD

**Issue by stayen** [mapcrafter/mapcrafter#330]
Using world113 branch; built manually on Ubuntu 18.04.2 (64-bit)

After having built, I have collected textures (into ~/.mapcrafter/textures )

Config file:

    output_dir = ./Tenngrith
    
    [world:Tenngrith]
    input_dir = Tenngrith_input
    dimension = overworld
    
    [map:map_Tenngrith]
    name = Tenngrith
    world = Tenngrith

Before launching mapcrafter, I copied the saved game files into Tenngrith_input

Command:

    mapcrafter -c Tenngrith.conf

It works for approx. a minute (on a small world), but the generated map is empty (all graphic files are fully transparent .pngs)

While rendering, mapcrafter issues no errors/complaints.

Shall I provide more information on the issue (I can send entire saved game if necessary).

**Comment by ligos** [comment]
You'd be needing the (rather experimental) `world114` branch for 1.14.

**Comment by stayen** [comment]
@ligos Is it a joke?

    $ git branch -a
      master
    * world113
      remotes/origin/HEAD -> origin/master
      remotes/origin/azeroth
      remotes/origin/big-fat-refactoring
      remotes/origin/cave_contrast_patch
      remotes/origin/corner-stairs-wtf
      remotes/origin/indexed-png
      remotes/origin/json-utf8-fix
      remotes/origin/legacy
      remotes/origin/mapcrafter-repo-warning
      remotes/origin/mapcrafter_library
      remotes/origin/master
      remotes/origin/mc1.8
      remotes/origin/over-9000-lays
      remotes/origin/pngquant
      remotes/origin/topdown
      remotes/origin/windows-debug
      remotes/origin/world113

I'd prefer more real-life pieces of advice.

**Comment by ligos** [comment]
Serves me right for not actually checking the source!
I meant this `world114` branch: https://github.com/miclav/mapcrafter/tree/world114
From this pull request: https://github.com/mapcrafter/mapcrafter/pull/327

**Comment by stayen** [comment]
@ligos Thanks for the reference - that actually works for 1.14.

I suppose I close the issue; until the fork is merged, it makes little sense asking about 1.14 here.
