### ISSUE TITLE
Reinstalling Mapcrafter

### ISSUE THREAD

**Issue by NerdieSanders** [mapcrafter/mapcrafter#333]
I think that I'm having an outdated version of Mapcrafter running on my Debian server, and I'd like to reinstall the program. However, I have no idea where or how to start this process. Tried following the steps on the installation in the documentations but to no avail.

**Comment by cliffmeyers** [comment]
I don't think anyone can help with this issue unless you provide some more information. Are you building from source or installing packages with apt? What error message(s) did you receive?

**Comment by QuestionTuesdayFTW** [comment]
Hi, I help NerdieSanders with running his Debian server. We run on 1.13 which as we know Mapcrafter has been having issues with (As per https://github.com/mapcrafter/mapcrafter/issues/275).

We tried a clean uninstall and reinstalling Mapcrafter using the 1.13 branch (https://github.com/mapcrafter/mapcrafter/tree/world113) using the installation steps provided in the documentation. 

It seems to install fine, but attempting to get a map of the world results in the same error code as the current branch of Mapcrafter. Not sure if this is a problem with not uninstalling properly or with the 1.13 branch.

**Comment by elamperti** [comment]
I hope you were able to solve it! Things should improve once #348 is merged (or you can try using the branch of that PR until it's merged). 

I'll be closing this issue, feel free to comment if new issues arise :)
