### ISSUE TITLE
Lighting issue when using blockcrafter custom block sprites

### ISSUE THREAD

**Issue by fredkilbourn** [mapcrafter/mapcrafter#336]
Minecraft 1.14.3

Using latest blockcrafter docker image, mapcrafter compiled from https://github.com/mapcrafter/mapcrafter/commit/2e33e0d7a67980fec758472cbb5106a773b115e9

When i use the distributed blocks folder, it renders fine (though limited to 16 texture size).

When i use the blocks folder i built with blockcrafter in October 2018, it renders fine but is missing the new 1.14 elements.

When i use the blocks folder i built with 1.14.3.jar today, it renders with large swaths of surface as black.  Looks like it may be tied to certain biomes.  Example:
![image](https://user-images.githubusercontent.com/658757/60552087-13854d80-9cf3-11e9-983d-69a943fce99e.png)

I've tried all kinds of variations of indexed or non indexed png, only using the official minecraft jar without my custom resource pack, different texture sizes, can't seem to build any way with blockcrafter where this isn't the result.

Ideas?  Help!

**Comment by elamperti** [comment]
Probably related to #287 and #299 (or missing updated textures?)

**Comment by fredkilbourn** [comment]
@elamperti whatever the issues were before are long fixed.  Latest mapcrafter and the blockcrafter PR https://github.com/mapcrafter/blockcrafter/pull/7 from @miclav have fixed this on 1.16.  I'm going to close.
