### ISSUE TITLE
Bamboo Jungle Biome not recognized

### ISSUE THREAD

**Issue by fredkilbourn** [mapcrafter/mapcrafter#337]
Using mapcrafter compiled from https://github.com/mapcrafter/mapcrafter/commit/2e33e0d7a67980fec758472cbb5106a773b115e9

```
[WARNING] [default] Unknown biome with id 168
```

**Comment by fredkilbourn** [comment]
Based on the wiki, i think both of these need to be added:

Name | Namespaced ID | Numeric ID
-- | -- | --
Bamboo Jungle Hills | bamboo_jungle_hills | 169
Bamboo Jungle | bamboo_jungle | 168

**Comment by elamperti** [comment]
It seems like #348 will solve this issue ([relevant lines](https://github.com/mapcrafter/mapcrafter/pull/348/files#diff-1fa76bda1b1137aaf37c314cf483caa4R161-R162))

**Comment by fredkilbourn** [comment]
That or something else has fixed this.
