### ISSUE TITLE
Certificate is expired

### ISSUE THREAD

**Issue by DutchFlander** [mapcrafter/mapcrafter#345]
Hi,

The webpage certificate (and for updating the binaries) is expired and cannot update to the newer version since today:
`sudo wget -O /etc/apt/trusted.gpg.d/mapcrafter.gpg http://packages.mapcrafter.org/debian/keyring.gpg
--2019-10-30 13:21:28--  http://packages.mapcrafter.org/debian/keyring.gpg
Resolving packages.mapcrafter.org (packages.mapcrafter.org)... 148.251.55.244, 2a01:4f8:201:8174:73::42
Connecting to packages.mapcrafter.org (packages.mapcrafter.org)|148.251.55.244|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://packages.mapcrafter.org/debian/keyring.gpg [following]
--2019-10-30 13:21:28--  https://packages.mapcrafter.org/debian/keyring.gpg
Connecting to packages.mapcrafter.org (packages.mapcrafter.org)|148.251.55.244|:443... connected.
ERROR: The certificate of ‘packages.mapcrafter.org’ is not trusted.
ERROR: The certificate of ‘packages.mapcrafter.org’ has expired.
The certificate has expired`

And the update:
`W: GPG error: https://packages.mapcrafter.org/debian stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B6F77E28FE4F4EAC
E: The repository 'http://packages.mapcrafter.org/debian stretch Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

I can disable key verification, but it is a security risk. The certificate must be renewed on server side.
I guess it is simply expired.

Sorry, if this is not the right place to address this issue, but I couldn't find any other...

Kind regards,
Dutch

**Comment by m0r13** [comment]
Sorry, the answer is too late probably, but for future cases:

SSL certificate has been renewed, and you have to download the key as described in the docs:
https://docs.mapcrafter.org/builds/stable/installation.html#debian-packages

`sudo wget -O /etc/apt/trusted.gpg.d/mapcrafter.gpg http://packages.mapcrafter.org/debian/keyring.gpg`
