### ISSUE TITLE
Support 1.14 biome format

### ISSUE THREAD

**Issue by elamperti** [mapcrafter/mapcrafter#351]
The current implementation in `world113` works with 1.13 and 1.15 biome formats, and considering the small changes between versions it may be possible to implement support for 1.14 as well with a few changes.

**Comment by elamperti** [comment]
As suggested by @cliffmeyers, it would be useful to suggest using `--forceUpgrade` to users with old maps as well.

@bemk also pointed out in #348:
>Another thing that's still missing, is that the biome data now also includes an elevation component. So a map maker would be able to stack multiple biomes on top of one another, but currently the biome data of the lowest 4x4x4 sub chunk is used by mapcrafter for the entire 4x4 column all the way up to build height.

**Comment by bemk** [comment]
If I recall correctly, I put the biome changes in for 1.14. I wouldn't be surprised if the 1.15 branch also works on a 1.14 world.

I should also clarify that inconsistencies in the vertical component of the biome information at this time are very much an edge case. Map makers might toy around with it, but as far as I've been able to tell, vanilla minecraft terrain generation is not using the new capabilities yet. This may change for 1.16 with the new nether though, but I haven't tested that.

**Comment by elamperti** [comment]
This seems to be working as expected in world113 after #347 was merged in miclav's fork and into world113 afterwards. Feel free to reopen the issue if I'm wrong. Thanks again bemk for your contribution :)
