### ISSUE TITLE
[WARNING] [default] Out dated chunk -354:226: Old biome data found!

### ISSUE THREAD

**Issue by jxu** [mapcrafter/mapcrafter#356]
I am trying to load a 1.13.2 world with world113 branch nightly release `mapcrafter_2.3.1~228~g25f3f4f_win64.zip`, and I get tons of messages about out dated chunks, and the map never renders.
Same happens for 1.14.4 world.

**Comment by jxu** [comment]
I even tried updating the 1.14.4 world to 1.15.2 but still same errors.

**Comment by elamperti** [comment]
@jxu have you tried starting the server with `--forceUpgrade`? (or visiting every chunk in-game to force the upgrade)

**Comment by jxu** [comment]
I tried force upgrade to 1.15.2 with optimize chunks (this is a single player world) and the error is 2020-05-27 22:16:09 [WARNING] [default] Corrupt chunk -169:-168: No biome data found!

Using nightly package 2.3.1~213~g2e33e0d on Ubuntu Xenial

**Comment by jxu** [comment]
In the 1.12.2 world I upgraded to 1.13.2 with optimize chunks and the map generated except for a lot of these errors: 

```
2020-05-27 22:34:56 [INFO] [default] Unknown block minecraft:sign waterlogged=false,
2020-05-27 22:34:56 [INFO] [default] Unknown block minecraft:wall_sign waterlogged=false,
```

so I guess it's a 1.15 issue

**Comment by elamperti** [comment]
I wasn't able to reproduce this issue locally with the latest world113 code, if this still happens for you with the latest code let us know. I'm closing this issue for now
