### ISSUE TITLE
Creating huge PNGs 

### ISSUE THREAD

**Issue by jxu** [mapcrafter/mapcrafter#359]
Currently png-it.py uses Pillow which has to load the entire image into memory.

I might be able to hack together a slightly modified version of the script instead using pyvips that can produce very large entire maps at high zoom. (I actually did something very similar for medical images at an internship) something like https://libvips.github.io/pyvips/vimage.html?highlight=insert#pyvips.Image.insert

what do you think?

**Comment by jxu** [comment]
I wrote this late last night and now that I think about it, most image viewers can't even handle images above 20000 x 20000

**Comment by elamperti** [comment]
@jxu What would be the benefit over the current implementation? (regardless of image viewers limitations)

**Comment by jxu** [comment]
Current implementation requires exponential memory for zoom levels. zoom lvl 9 requires 4 GB, zoom lvl 10 requires 16 GB, etc.

**Comment by jxu** [comment]
I created a test version that in theory works but it's much slower and mysteriously segfaults even though memory usage is not maxed out. Since people probably don't have use for absurdly huge images I'll just leave it.

https://github.com/jxu/mapcrafter/tree/huge-png-it
