### ISSUE TITLE
Error with 1.16 map generating

### ISSUE THREAD

**Issue by beulette** [mapcrafter/mapcrafter#369]
After merging world116, I have fewer issues, but still no map generated.

Here is the log :
> me@server:~# root@serveurBeulette:/home/minecraft/server# mapcrafter -c /var/www/mapcrafter/render.conf -j 4
> 2020-07-01 23:13:00 [INFO] [default] Scanning worlds...
> 2020-07-01 23:14:14 [INFO] [default] [1/2] Rendering map map_world ("Le Monde"):
> 2020-07-01 23:14:14 [INFO] [default] [1.1/1.4] Rendering rotation top-left...
> 2020-07-01 23:14:14 [INFO] [default] Last rendering was on 23 Jun 2020, 05:00:02.
> 2020-07-01 23:14:14 [INFO] [default] Scanning required tiles...
> 2020-07-01 23:15:56 [INFO] [default] I will load block images from "/usr/local/share/mapcrafter/blocks" now
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -147:-412: No biome data found!/95295 0.21/s ETA 5d 5h         
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -148:-412: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -149:-412: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -151:-412: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -152:-412: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -153:-412: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -154:-412: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -154:-411: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -155:-411: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -156:-411: No biome data found!
> 2020-07-01 23:15:58 [WARNING] [default] Corrupt chunk -152:-411: No biome data found!
> 2020-07-01 23:15:58 [ERROR] [default] Incorrectly parsed palette ID 20 at index 551 (max is 17 with 5 bits per entry)
> *** stack smashing detected ***: mapcrafter terminated
> Aborted

Seems to be the same error that happened found in commentary here : 
https://github.com/mapcrafter/mapcrafter/issues/363#issuecomment-649639077

**Comment by elamperti** [comment]
* Have you ran your minecraft server with `--forceUpgrade` to update the whole world?
* Which branch/commit did you use to build mapcrafter?

**Comment by beulette** [comment]
My bad, I did the forceUpgrade now, but the issue is still here somehow.
I update the original post with the last error log.
Mapcrafter building was made throught world113. I had issues with world116 "make".

**Comment by beulette** [comment]
I'll close the issue, I can't find how to compile (errors with boost) and I k now nothing about this, so it's not the good place for it ;-)
