### ISSUE TITLE
[Feature Request] Add a pid/lockfile so multiple instances can't run at the same time

### ISSUE THREAD

**Issue by fredkilbourn** [mapcrafter/mapcrafter#371]
Would be nice so i don't have to worry about a long run still being active by the next my next cron schedule hits.

**Comment by elamperti** [comment]
This may conflict with existing or future setups where multiple instances are desired. You can solve it in your crontab/script using:

```
pgrep -x mapcrafter || your/mapcrafter/bin/or/script/here
```

**Comment by fredkilbourn** [comment]
thanks i did something based on that
