### ISSUE TITLE
Unknown biome id 173 (Basalt Deltas)

### ISSUE THREAD

**Issue by Sicarine** [mapcrafter/mapcrafter#372]
Recently managed to build from source for the first time. If I am not mistaken, I built off of commit d3b2ed......

The map built just fine. Just got this error in the command line:
![image](https://user-images.githubusercontent.com/43017668/86597099-2c25e480-bf93-11ea-94ee-84a018f6ff25.png)

173 seems to be the id for basalt deltas.

The map was rendered alright regardless, so it isn't a huge issue, but just wanted to put it on the tracker.

Excellent work with the renderer.

**Comment by miclav** [comment]
This bug is fixed by [this commit](https://github.com/miclav/mapcrafter/commit/532d005b016605071bcec1933be9032f46ccb025)
It can easily be cherry picked.
