### ISSUE TITLE
Map not showing up

### ISSUE THREAD

**Issue by Dechetmew** [mapcrafter/mapcrafter#377]
I know, this issue was already poste by someone else but i have more problems. I just rendered a world and when opening index.html file, it was showing nothing in the browser. Pure nothing. I tried adding crop radius 5000 but that didnt help. i also tried lowering the number to 4000 then 3000, 2000 and 1000 and still no help.

Here is the Configuration File:

[world:blank - kópia 13,4,2020 Save]
input_dir = worlds/blank - kópia 13,4,2020 Save
crop_center_x = 0
crop_center_z = 0
crop_radius = 1000

[map:map_blank - kópia 13,4,2020 Save]
name = blank kopia 13 4 2020 save
world = blank - kópia 13,4,2020 Save

**Comment by elamperti** [comment]
@Dechetmew 
  * Does the output folder contain tiles? (i.e. does it render any image)
  * Which mapcrafter version are you using?
  * What is the console output when you run mapcrafter?

Try using a more computer-friendly name (that is: no spaces or symbols in the name, perhaps even drop the `ó` for the sake of testing)

**Comment by Dechetmew** [comment]
Thanks, it solved the problem. I didnt know that these letters can be a problem. It was written in Slovakian.

**Comment by elamperti** [comment]
I'm glad you solved it! Closing the issue :)
