### ISSUE TITLE
[Windows] environment:locale::facet::_S_create_c_locale

### ISSUE THREAD

**Issue by Beanster199** [mapcrafter/mapcrafter#378]
Trying to run my ./mapcrafter.exe on PowerShell but getting next error: 

>   There seems to be an issue with your locale, please verify your environment:locale::facet::_S_create_c_locale name not valid
>   terminate called after throwing an instance of 'std::runtime_error'
>     what():  locale::facet::_S_create_c_locale name not valid

I know this isn't a mapcrafter issue but any help is well apreciated

Im running on Windows, already tried changed my locale but seems doesn't work. Any Suggestion ?

**Comment by filipobradovic** [comment]
run away from windows

**Comment by autowert66** [comment]
Can you try again in PowerShell outside VS Code?
This might be caused by VS Code changing the Environment-Variables.
