### ISSUE TITLE
Unknown tag type with id 12. NBT data stream may be corrupted.

### ISSUE THREAD

**Issue by otse** [mapcrafter/mapcrafter#379]
Dear MapCrafters,

No matter which release I download, or which world version I try to render, I only get unlimited errors no matter what I do.

I feel... dumb. I'm making pixel art with dynmap but need something that's a little griddier. I would like to know how to use this, but it seems 100% impossible and I really tried.

What is causing this error?

Thanks! P

**Comment by elamperti** [comment]
Hi @otse, would you mind sharing the error(s) you get, version of the map (usually your minecraft server version), version of mapcrafter and on which operating system you are trying to run it?

**Comment by otse** [comment]
Hi,

The version I use is mapcrafter_2.3.1_win32 and I've tried 64 too. I think I tried different mapcrafte builds even.

The maps I've tried are 1.14 worlds and 1.16 worlds.

I run on Windows 10. I checked that it doesn't "block" the dll or executables or the zip, that can be an issue on my system (for downloaded files).

Edit: I've tried Flat worlds and normal seed worlds.
Edit: Tl;dr always same error

My config file is super simple.

![image](https://user-images.githubusercontent.com/1123362/96728450-6c7b6800-13b4-11eb-8db7-ae0aae95367a.png)

**Comment by elamperti** [comment]
Have you tried the nightly version? https://mapcrafter.org/downloads/nightly
(try with the latest one, `2.3.1~275~g12ce56d`)

**Comment by elamperti** [comment]
I'll consider this one solved, feel free to comment/reopen the issue if it wasn't  :slightly_smiling_face:

**Comment by Alexey0795** [comment]
I have the same error output
![errscr](https://user-images.githubusercontent.com/67856095/117936666-cec69680-b30d-11eb-9ffa-aaa2a48dbe21.png)
1.16.5
2.3.1 ~ 275 ~ g12ce56d

my render.conf file:
output_dir = F:\Downloads\mapcrafter_2.4_win64\mappViews

[world:MySavedWorld]
input_dir = F:\Downloads\mapcrafter_2.4_win64\saves\MySavedWorld

[map:myworld_isometric_day]
world = MySavedWorld
