### ISSUE TITLE
I keep getting a blank page after rendering

### ISSUE THREAD

**Issue by FruitCircuit** [mapcrafter/mapcrafter#381]
So this was my fist time rendering using mapcrafter, I tried to render a 700MB minecraft world of a server. It is 1.16.4.
First I downloaded the latest nightly package for windows from the mapcrafter website, then I put a copy of the world folder in the "worlds folder". Then I opened the GUI and copied some code from the documentation and replaced everything with the name of the world folder:-
output_dir = output

[world:servermap]
input_dir = worlds/servermap

[map:servermap]
name = servermap
world = servermap

Then I clicked render! And... First i get a few errors saying: "Corrupt region (some region.mca file??) header is too short"
Then it starts rendering scanning tiles etc
Then MORE errors! Loads of: Unknown block: sandstone_wall and Unknown block: cobblestone_wall (east west south north waterlogged=false etc)
Then it finishes, I go to the output folder, open the index file and i get a blank page.
What am I doing wrong?? Please help.

**Comment by Ycooldude** [comment]
i can send screenshots if needed btw thanks :)

**Comment by quizhizhe** [comment]
Is your world transferred from Bedrock Edition?

**Comment by elamperti** [comment]
Mapcrafter was built for java edition, if the map is from bedrock it may not render correctly or at all. If it isn't the case and this still happens with the latest changes in the branch `world113` (latest nightly) please reopen the issue.
