### ISSUE TITLE
Quick help

### ISSUE THREAD

**Issue by GL4D1AT0R** [mapcrafter/mapcrafter#393]
Can we make take all 6 renders and convert it into a world which is playable. Just curious if thats possible. 
![image](https://user-images.githubusercontent.com/84785529/167868785-db369746-889d-4f9c-9004-48614e6e9604.png)

**Comment by miclav** [comment]
Hi
I'm not sure if I understand the question, as it sounds far fetched, but if you want to convert a map into a real world it's not possible, as the map is only displaying a small fraction of data that a real world would need to work properly.
