### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by AlecZadikian9001** [mapcrafter/mapcrafter#69]
I've installed this in Debian using the Debian package. I'm getting a segmentation fault a few seconds into the rendering step. This is on an x86 Mac (Mac Pro 3,1) running 32-bit Debian 7.4 (latest) in VirtualBox with 1GB of RAM dedicated to the VM. My setup:

Working directory is /home/alecz/Desktop
Desktop contains mapcraftconfig as the config file and hwmcc as the world dir
I'm running mapcrafter -c mapcraftconfig

My config file:

output_dir = /home/alecz/Desktop/map

[world:myworld]
input_dir = /home/alecz/Desktop/hwmcc

[map:map_myworld]
name = HWMCC
world = my world

Log:

alecz@debian:~/Desktop$ mapcrafter -c mapcraftconfig -j 8
Scanning worlds...
(1/1) Rendering map map_myworld ("HWMCC"):
(1.1/1.1) Rendering rotation top-left:
Scanning required tiles...
8 threads will render 43978 render tiles.
Segmentation fault

**Comment by m0r13** [comment]
I added better validation and error messages of broken chunks/regions a while ago. Guess we can close this now.
