### ISSUE TITLE
Cobblestone walls have incorrect appearance

### ISSUE THREAD

**Issue by rockmacaca** [mapcrafter/mapcrafter#89]
Currently cobblestone walls appear exactly the same as wooden fences when they should look different visually. I realize they probably share the exact same code, but the actual appearance is no more complicated the wood fences. They also should connect to fence gates.

**Comment by konimaru** [comment]
FWIW, MinecraftOverviewer gets them right.

**Comment by m0r13** [comment]
Mapcrafter supports different texture sizes, that's why I'm struggling a bit with the implementation of these blocks in the 3D isometric render view. In the 2D topdown view cobblestone walls look like in-game.

**Comment by memiux** [comment]
Overviewer
![overviewer](https://cloud.githubusercontent.com/assets/37290/11672605/ac6d9e72-9dd7-11e5-8f73-cf0e81f9a593.png)

Mapcrafter
![mapcrafter](https://cloud.githubusercontent.com/assets/37290/11672608/b5458ef6-9dd7-11e5-8076-a57c8fe4e187.png)


```
output_dir = public

[global:map]
world = world
render_view = isometric
texture_size = 16
image_format = jpeg
jpeg_quality = 90

[world:world]
input_dir = worlds/world
default_zoom = 3

[map:world_isometric_day]
name = World - Day
render_mode = daylight
rotations = top-left top-right bottom-right bottom-left
water_opacity = 0.75
lighting_water_intensity = 0.6

[map:world_isometric_night]
name = World - Night
render_mode = nightlight
rotations = top-left
```

**Comment by m0r13** [comment]
Yeah, they look a bit more fancy. If you guys would like new features and don't like the existing block appearance in Mapcrafter, why not do a PR?

I'm the only developer of this project and quite often there are other things I want to do or other projects I have to work on.

</rant> sorry ;)
